### ISSUE TITLE
Support tokens in number properties

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-style-spec#105]
Would allow for vector tile data in style properties, like:

```json
{
   "icon-size": "{venue_rating}"
}
```

cc @ansis @mourner

**Comment by robschley** [comment]
Has there been any movement on this feature? What would it take to get it added to the spec? Can I help in any way?

**Comment by jfirebaugh** [comment]
@robschley No movement, though it's relatively hight on the priority list. The spec change is straightforward; the main lift would be implementing it in mapbox-gl-js and mapbox-gl-native.

**Comment by lucaswoj** [comment]
@robschley In the mean time, I humbly suggest taking a look at https://github.com/scree-maps/scree-ss

**Comment by jfirebaugh** [comment]
⇢ https://github.com/mapbox/mapbox-gl-style-spec/issues/249
