### ISSUE TITLE
Support sdf images for fill-pattern and line-pattern

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#117]
Is it a possibility to enable use of sdf images as fill patterns, with some of the same properties available for sdf icons (size, color, etc)? Would this kill performance, or otherwise be a bad idea?

/cc @ansis @edenh

**Comment by lucaswoj** [comment]
Lets discuss support for `fill-pattern` _and_ `line-pattern`!

**Comment by lucaswoj** [comment]
Closing in favor of #444 and https://github.com/mapbox/mapbox-gl-js/issues/3605
