### ISSUE TITLE
dropping -rotation-alignment property

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-style-spec#137]
Currently: If placement-type is "point" it uses each point in the geometry as an anchor. If placement-type is "line" it interpolates the geometry to create anchors. "point" labels are aligned with the viewport by default. "line" labels are aligned with the geometries and the map. To make horizontal labels interpolate along a line, `"text-placement-type": "line", "text-rotation-alignment": "viewport"` is used.

Would it make more sense if `-placement-type` controlled the alignment, and the interpolation was based on the feature type (lines always get interpolated)? We could then drop the `-rotation-alignment property`.

@kkaefer @mourner

**Comment by lucaswoj** [comment]
Are we still considering dropping this feature? I infer that that our expansion into `pitch-alignment` properties indicates that this type of control is useful and used. Please re-open if I'm wrong.
