### ISSUE TITLE
URL Template? + retrive

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#151]
![2014-09-10 at 3 04 pm](https://cloud.githubusercontent.com/assets/32314/4226323/6f136e28-3936-11e4-9f38-4d9e3fbec51f.png)

Misspelling, but also, if a template, what kind? what kind of things would be replaced and when and why.

**Comment by bhousel** [comment]
This seems fixed in v8, all the `url` properties have better documentation now.
