### ISSUE TITLE
Link or nest style and render properties of layer

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#156]
Found this confusing on my reading

![2014-09-11 at 11 42 am](https://cloud.githubusercontent.com/assets/32314/4239715/6aa3a9a4-39e3-11e4-9cda-c7f0eef50871.png)

![2014-09-11 at 11 42 am](https://cloud.githubusercontent.com/assets/32314/4239722/753eb75a-39e3-11e4-9825-14df462ec051.png)

Looks like the former should link to or contain the latter, but their relation is not explicitly mentioned at all in this page.

**Comment by jfirebaugh** [comment]
Should be better now that the whole thing is organized by layer type.
