### ISSUE TITLE
Allow developers to add GeoJSON source and style layer in one step

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-style-spec#162]
Currently adding some data to a map is a lot of hassle. E.g. if you need to add GeoJSON, you have define a layer for each type of feature (line, fill, symbol), set styles for each, etc.

We should make it dead easy to do without even touching the stylesheet, Leaflet-style. This will enable us to create UIs like surface stuff by @dnomadb much faster.

Something like:

``` js
var poly = mapboxgl.polyline(points).addTo(map);
...
poly.addLatLng(point);
```

So what I'm thinking, just a starting point to discuss:
- have a default source overlays go into if not specified (e.g. `default_source`)
- have default layers for each feature type with default styles and set to default source (e.g. `default_line`, `default_fill`)
- you can define all the default layers in the stylesheet, setting your own styles, z-place among layers etc. for each layer, that inherit styles from some default styles (e.g. render lines as 5px red by default)
- all default layers that are not defined in your stylesheet are just appended to the stylesheet at the front

@edenh @tmcw @kkaefer @ansis @dnomadb

**Comment by lucaswoj** [comment]
This is a very common complaint about the erganomics of our API.

An alternate proposal that avoids the need to invent a new abstraction layer for our library is allowing "inline" source declarations:

```js
map.addLayer({
     "type": "line",
     "source": {
        type: "geojson",
        data: {
          "type": "FeatureCollection",
          "features": [
            {
              "type": "Feature",
              "properties": {},
              "geometry": {
                "type": "LineString",
                "coordinates": [
                  [
                    -172.96875,
                    -28.30438068296277
                  ],
                  [
                    -67.5,
                    72.39570570653261
                  ]
                ]
              }
            }
          ]
        }
     },
     paint: {
         "line-color": "blue"
     } 
})
```

**Comment by mourner** [comment]
That's a nice idea! Easy to implement and an instant improvement of ergonomics in many cases. The source would then have the same `id` as the layer, right?

**Comment by lucaswoj** [comment]
Thanks @mourner. 😄 Giving the source & layer the same `id` is a good idea. That'd make it easy to reference the source again from other layers. The one challenge is figuring out what to do in the unlikely event of a name collision.

**Comment by jfirebaugh** [comment]
We could require that the `id` be unused among both layer IDs and source IDs. (Not in general, just when `addLayer` is used in this way.)

**Comment by jfirebaugh** [comment]
This was implemented.
