### ISSUE TITLE
Document "*-transition" properties

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#171]
Document how `*-transition` properties work.

**Comment by lucaswoj** [comment]
Both gl-js and gl-native support setting paint-property specific transition options. For example,the `circle-radius` transition may be controlled by setting the property `circle-radius-transition`. This should be clearly documented. 

cc @danswick

**Comment by lucaswoj** [comment]
I just identified a minor outstanding bug related to this https://github.com/mapbox/mapbox-gl-js/issues/1996

**Comment by peterqliu** [comment]
I'm interested in working on this, as it's required for setting transition durations at runtime with `.setPaintProperty`. Is there some way we can generate these (very repetitive) entries in an automated fashion, or are we stuck writing these manually?

**Comment by lucaswoj** [comment]
@peterqliu I think we can document this feature with a paragraph and some examples in the in the ["Transition" section](https://www.mapbox.com/mapbox-gl-style-spec/#transition). Reading an entry per paint property would be as repetitive as writing them!

**Comment by mollymerp** [comment]
This is an easy fix and something we should hit asap. @peterqliu do you want to knock this out ? Happy to jump in if not.

**Comment by lbud** [comment]
Came up again in https://github.com/mapbox/mapbox-gl-js/issues/4045

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4081
