### ISSUE TITLE
dasharray what does it mean

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#176]
![2014-10-01 at 4 52 pm](https://cloud.githubusercontent.com/assets/32314/4482930/ed204b7a-49ac-11e4-9355-0a6aa12d97dd.png)

**Comment by jfirebaugh** [comment]
@ansis can you update/improve the `line-dasharray` description for v7?

**Comment by ansis** [comment]
Sorry about missing this issue a couple months ago.

511790a updates it for v7:

"Specifies the lengths of the alternating dashes and gaps that form the dash pattern. The lengths are later scaled by the line width. To convert a dash length to pixels, multiply the length by the current line width."

> I did hit a weird shimmering effect at [0.5, 0.5]

http://en.wikipedia.org/wiki/Aliasing
