### ISSUE TITLE
Make property names use nouns rather than verbs (for example "rotate" ⇢ "rotation")

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#201]
Rationale:
- Properties use nouns wherever possible, not verbs.
- Match *-rotation-alignment.

**Comment by lucaswoj** [comment]
Also `symbol-avoid-edges` -> `symbol-allow-edge-overlap`

- is more consistent with the naming of `icon-allow-overlap` and `symbol-allow-overlap`
- prevents users from having to think in double negatives

**Comment by tmcw** [comment]
Another benefit to this change is that it'd reduce the [difference between the iOS SDK's reinterpretation of properties](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/scripts/style-spec-cocoa-conventions-v8.json) and the style spec / gl-js's interface to them. It's a breaking change, which is a bummer, but I think it's worthwhile on a fixing-the-system level and also makes good sense.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4082
