### ISSUE TITLE
explicit layer visibility property

### ISSUE THREAD

**Issue by donpark** [mapbox/mapbox-gl-style-spec#212]
I've been looking at two bundled styles, bright and outdoors, looking for ways to cleanly (no warning messages) hide layers.

Unless I'm mistaken, my options are:

1. delete layer from style JSON - destructive change makes ad-hoc experiments cumbersome.
2. overide layer by adding another layer with same ID - haven't tried because it's a hack that depends on styler implementation.
3. add empty filter or modify existing filter to fail - again, destructive change

Is there a built-in attribute specifying visibility of a layer?

Beyond this need, I would like to know if ability to change visibility of one or more layers (via some grouping mechanism at style JSON level) at runtime is planned.

**Comment by lbud** [comment]
bump — is there a good reason why we *shouldn't* implement a `hide: true` property?

**Comment by lbud** [comment]
(This also seems like it would be good to have with a layer mutation API like https://github.com/mapbox/mapbox-gl-js/issues/755 )

**Comment by jfirebaugh** [comment]
What, concretely, is the advantage of an explicit `hide: true` property over `opacity: 0`? How would you expect transitions work across a change to this property?

**Comment by peterqliu** [comment]
>What, concretely, is the advantage of an explicit hide: true property over opacity: 0?

- the specific opacity property varies with the layer type (`fill-', 'line-', 'background-', 'raster-'), and we'd have to assemble the appropriate property key string on every hide event.
- hiding by setting opacity to 0 means we have to store that original opacity value somewhere, to be restored when the layer gets un-hidden. A dedicated `hide` property sidesteps this.

**Comment by jfirebaugh** [comment]
You didn't answer the second question. :)

In almost all cases, you want to fade the layer in or out when hiding or showing it, right? And in those cases you would need to fiddle with the appropriate opacity setting, and remember it's original value when hidden, regardless of whether `hide: true` is possible. So I'm not seeing how `hide: true` makes things simpler -- it seems to me it just adds one more piece of state you need to track.

**Comment by lbud** [comment]
Re: the desire to fade out — true, but this still seems like (a) a helpful linguistic abstraction for the user, and (b) helpful for the remembering-opacity thing. In my mind this would *function* like an `opacity: 0` property, but would just make it easier to mutate externally.

**Comment by jfirebaugh** [comment]
So setting `hide: true` would automatically transition a different property? That's something that no other style property does, so we'd be introducing a new thing we have to document and define behavior for. E.g. what happens if you change both `hide` and `*-opacity` at once -- how does the combined transition work? Are you allowed to set a duration/delay on `hide-transition`? Both `hide-transition` and `*-opacity`?

**Comment by peterqliu** [comment]
>what happens if you change both hide and *-opacity at once 
Think of `hide` as separate, but overriding property to `opacity`, like `display` in CSS. If `true` (`display:none`), nothing is visible, regardless of opacity. If `false`, it defers to opacity.

**Comment by peterqliu** [comment]
@jfirebaugh and as for your second question, I actually use transitions sparingly, and opt for opacity or line-width transitions in those cases :)

**Comment by jfirebaugh** [comment]
Sorry folks, I'm totally not convinced on this one. [Dealing with transitions across changes to `display` in CSS is a pain](http://stackoverflow.com/questions/3331353/transitions-on-the-display-property), I definitely don't think we should emulate it.

**Comment by tmcw** [comment]
I'm :+1: for this acting as a boolean and 'popping' instead of transitioning.

Using `opacity:0` because it's transitionable would have the same head-scratch-effect as CSS: an element without opacity still occupies space, affects labeling, and may sit in the `.featuresAt`-reached rtree.

**Comment by ljbade** [comment]
It would also make it more obvious that the layer should not consume CPU/GPU time by being rendered.

**Comment by donpark** [comment]
my two cents worth: why not just make it a simple convenience filter on top of opacity feature? If it's true, suppress stroke and fill opacities to zero. If false, remove suppression. No transition necessary when it's state is just true or false. For bonus points, turn it into an extension point to support custom attributes affecting one or more built-in attributes.

**Comment by mourner** [comment]
Agree with @tmcw — :+1: to `hide: true`: no transition, doesn't affect placement, never present in feature tree.

**Comment by peterqliu** [comment]
> If it's true, suppress stroke and fill opacities to zero. If false, remove suppression. No transition necessary when it's state is just true or false. 

@donpark I think you and I are saying the same thing here :+1:

**Comment by jfirebaugh** [comment]
Ok, we're doing this. But let's follow CSS and make this "visibility" with values "visible" (default) and "collapse" (open to alternatives here). There's a possibility we'll want to add a "hidden" value which hides the features but still considers them for placement.

**Comment by lbud** [comment]
Cool. So, 
* still pop, rather than transition, right?
* should this be a `layout` property or a top-level layer property?

**Comment by jfirebaugh** [comment]
Yes, layout property, which implies no transition.

**Comment by lbud** [comment]
I kinda hate "collapse." What about `visibility: [visible, hidden, none]`…or something? ("hidden" would still consider placement) I know that's a CSS visibility/display mashup but "none" sounds more logical?

**Comment by jfirebaugh** [comment]
`visibility: [visible, placement, none]` ?

**Comment by lbud** [comment]
:+1:

**Comment by lbud** [comment]
Should this apply to all layer types, or all but `background`? In the modified spec here I wrote it into all types but didn't yet add a case to parse layer properties for background types in gl-native as there hasn't been one thus far.

**Comment by jfirebaugh** [comment]
All layer types including `background`.
