### ISSUE TITLE
Drop prefixes in property names

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-spec#218]
![screen shot 2014-11-17 at 12 29 46 pm](https://cloud.githubusercontent.com/assets/4551508/5077130/794b9e5c-6e55-11e4-94b4-60300eb108d0.png)

Namely, `fill-`,`line-`,`raster-`,`background-`

These prefixes automatically take after the layer's `type`, and as long as they live on separate layers, are redundant. The other prefixes `icon-` and `text-` are necessary, since they can cohabit the same `symbol` layer.

**Comment by jfirebaugh** [comment]
Keeping these for now.

**Comment by 1ec5** [comment]
Dropping the redundant prefixes would be highly desirable for the iOS and macOS SDKs, where property names are expected to be grammatical: https://github.com/mapbox/mapbox-gl-native/issues/6577#issue-180968544. As of mapbox/mapbox-gl-native#7457, we have to twist the English language in weird ways to ensure that Boolean property names in particular use the right parts of speech.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4083
