### ISSUE TITLE
Treat "images" as nested collection of a style, like sources or layers

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#220]
We want something more convenient than the current automagical practice of appending permutations of `.json`, `.png`, and `@2x` to the `sprite` property and making requests to two separate resources which need to be in sync.

Options that have been proposed:
- **External protobuf container** A format inspired by glyph pbfs. The protobuf message would be a series of [metadata, image data] tuples. Metadata would be id, image format, pixel ratio, and sdf boolean. Open question: would we still have separate @1x and @2x files, or just use @2x images everywhere, or permit including multiple images per id (with different pixel ratios) in the same file?
- **Inline JSON + base64 image data** Include sprite data directly in the style. Metadata in JSON format, image data base64 encoded ([can't really do better than that](http://stackoverflow.com/questions/1443158/binary-data-in-json-string-something-better-than-base64)). Same question regarding @2x images as above.

@mapbox/gl

**Comment by jfirebaugh** [comment]
I think we should:
- Eliminate the "sprite" concept and terminology. Instead a style has a collection of icons.
- Icons are embedded directly as an `"icons"` property of the style.
- An icon has a style spec JSON representation consisting of dimensions, pixel ratio, content type, and base64 encoded data. Content type must be PNG for now.
- The style API in gl-js (https://github.com/mapbox/mapbox-gl-js/issues/2058 / https://github.com/mapbox/mapbox-gl-js/issues/2059) and gl-native will be a standard CRUD API for the "icon" subresource of a style.
- `api.mapbox.com/styles/v2` renames the "sprite" subresource to "icons", but the interface is basically the same.

**Comment by ansis** [comment]
> Icons are embedded directly as an "icons" property of the style.

Would there be different styles for different device pixel ratios?

**Comment by jfirebaugh** [comment]
Multi-resolution support is TBD. But for starters, I think we could have Mapbox APIs always serve styles containing `@2x` icons, and for homesteaders, leave it up to them what resolutions they include with a style.

**Comment by scothis** [comment]
> > Icons are embedded directly as an "icons" property of the style.
> 
> Would there be different styles for different device pixel ratios?

If we make inlining optional, we can preserve a link to the icons resource that can be loaded resolution independent, or with a new images format. There are advantages to inlining and externalizing depending on the circumstance.

**Comment by ansis** [comment]
> I think we could have Mapbox APIs always serve styles containing @2x icons

This would kill pixel snapping for icons for 1x devices, which could be ok, but could also make icons too blurry at that size and resolution.

2x icons on 1x device:
![screen shot 2016-02-04 at 1 06 27 pm](https://cloud.githubusercontent.com/assets/1421652/12829703/596c469c-cb40-11e5-9035-7284dba1f35d.png) ![screen shot 2016-02-04 at 1 05 53 pm](https://cloud.githubusercontent.com/assets/1421652/12829706/596d533e-cb40-11e5-9785-84bb39b9bd5e.png) ![screen shot 2016-02-04 at 1 05 24 pm](https://cloud.githubusercontent.com/assets/1421652/12829707/5971c900-cb40-11e5-93ad-58bec9689fdc.png)

1x icons on 1x device:
![screen shot 2016-02-04 at 1 06 48 pm](https://cloud.githubusercontent.com/assets/1421652/12829702/596a4306-cb40-11e5-8688-9f7392ea1214.png) ![screen shot 2016-02-04 at 1 07 03 pm](https://cloud.githubusercontent.com/assets/1421652/12829704/596d268e-cb40-11e5-8357-545ba453ae1e.png) ![screen shot 2016-02-04 at 1 07 51 pm](https://cloud.githubusercontent.com/assets/1421652/12829705/596d616c-cb40-11e5-9315-17fbc1a771af.png)

**Comment by mourner** [comment]
Would images for patterns (fill textures etc.) also be called icons?

**Comment by jfirebaugh** [comment]
@mourner Good point -- the terminology should be consistent within the rendering property names as well. How about: `images`, `icon-image`, and `{background,fill,line}-pattern-image`?

**Comment by jfirebaugh** [comment]
Thoughts on pixel ratios:
- I'm warming to the idea of having the API be able to generate styles with images of a particular pixel ratio. In general I think Style API v2 should start to make a distinction between "raw"/"uncompiled" and "for-renderer"/"compiled" forms of a style and the desired pixel ratio could be part of the latter.
- However, I think we should preserve the ability to (hand-)author a single style document containing images at multiple resolutions and have the optimal resolution selected at render time. This has implications for how we structure the `"images"` style property and its sub-objects in the style. (Array or object? If object, what form are the keys in?)
- I'm not sold on the advantage of optional inlining. I think many of the problems we have encountered with sprites are due to the fact that a style isn't as self-contained as possible. Self-contained-ness just makes things way simpler. I'd like to push for inlining sources as well.

**Comment by lucaswoj** [comment]
I worry about the naming collision between "images" as proposed in this ticket and the `image` source type. Users may become confused that the same word can refer to either thing. 

cc @1ec5 @tmcw

**Comment by 1ec5** [comment]
…should image sources be called something else? 🤔

We have raster layers and raster sources; seems like style images and image sources could coexist at least as well.

How would you describe the difference between the two? Reusable images versus georeferenced images?

**Comment by lucaswoj** [comment]
Raster layers consume raster sources. That makes sense 👍.

Image sources would not relate to "images" (by some definitions of the thing). That makes a less sense to me.

**Comment by lucaswoj** [comment]
We could continue to call these new things "sprites" though we change how sprites are specified.

**Comment by anandthakker** [comment]
I may be missing some context or reading too fast here, but: if this is a replacement for `sprite`, could it still just be called `sprite`?

**Comment by 1ec5** [comment]
Regardless of the outcome of this discussion, it’s highly unlikely that we’ll ever introduce a “sprite” API to the iOS SDK or macOS SDK due to likely developer confusion. By far the most natural option on the platform would be “style image” (or more generally, “style asset”).

“[Sprite](https://developer.apple.com/library/content/documentation/GraphicsAnimation/Conceptual/SpriteKit_PG/Sprites/Sprites.html)” is the most fundamental concept in Apple’s SpriteKit framework, akin to a view in UIKit and AppKit. (The closest analogue to GL sprites in SpriteKit is a “texture”. The closest analogue to SpriteKit sprites in GL is a symbol layer.) Meanwhile, a typical iOS SDK developer will never know about sprite sheets or even style JSON. The style specification’s current use of the word “sprite” makes a lot less sense in the absence of a sprite sheet.

iOS doesn’t wield veto power over style specification naming decisions, but it would be unfortunate if we call these images “sprites” in the name of disambiguation, only to face ambiguity in practice. We expect [`-[MGLStyle setImage:forName:]`](https://www.mapbox.com/ios-sdk/api/3.4.0-beta.3/Classes/MGLStyle.html#/c:objc%28cs%29MGLStyle%28im%29setImage:forName:) to be used at least as much as Studio’s sprite editor among iOS developers – and far more than manual authoring of style JSON.

**Comment by lucaswoj** [comment]
`[MGLStyle setImage:forName:]` in iOS is a less ambiguous name than the proposed `Map#addImage` in Javascript. I would expect `Map#addImage` to add an image to the map. Associating this terminology with the style helps, for example `Map#addStyleImage` 👍

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4086
