### ISSUE TITLE
Support using multiple "source layers" in one "style layer"

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-spec#224]
One use case: 

![screen shot 2014-11-24 at 2 23 17 pm](https://cloud.githubusercontent.com/assets/4551508/5174510/b60c0b10-73e6-11e4-9e3a-c08b49370313.png)

Roads and freeways often cross over/under others instead of intersecting. The overpasses are classified `source-layer:bridge`, but are actually continuous with the surface sections, to form one stretch of road. Likewise, I style both sections the same way, to avoid a disjointed feel as the eye follows one road.

Instead of keeping track of separate layers for `bridge` and `road` sections, I'd like to select multiple source-layers in one style layer, much like the way we filter by class.

EDIT: this isn't the most ideal example, because bridges and roads have to be separated to articulate their stacking order. But it would still be good to be able to combine multiple source-layers, as that seems like an arbitrary limitation.

cc @jfirebaugh

**Comment by jfirebaugh** [comment]
This makes sense to me and easy to implement on the renderer side. My only question would be whether to rename `source-layer` to `source-layers` (and make the value an array), or to remove `source-layer` and add a `$layer` key to filters (analogous to `$type`). The latter is more pleasing from a spec point of view but does mean that feature filtering is fully O(features * layers), whereas right now `source-layer` allows efficient culling of most layers before running the features through the filter. (It should be possible to statically evaluate the filter and reapply this optimization for filters of the form `($layer = A OR $layer = B OR ...) AND (...)` but that adds additional complexity.)

This proposal is essentially a subset of #231 (Decoupling styling structure from source structure), but is easier than a full decoupling.

**Comment by peterqliu** [comment]
@jfirebaugh the latter is definitely good for making stylesheets more concise, because `$layer` becomes an optional filtering method that users invoke only when necessary (which would be uncommon, since `class` usually implies the source-layer anyway). It'd be great if we can do this without significant performance hits.

One question, though: what does a layer look like with no `source-layer` and no filters? Would it show nothing, or everything? Right now, `source-layer` is additive (defines what to include) while `filter` is subtractive. But if we combine the two, that distinction goes away.

**Comment by lbud** [comment]
I would *definitely* be in favor of the former (make `source-layers` an array). Filters right now feel/are very optional, and you would never want this to feel optional. So,
``` json
{
    "id": "water",
    "type": "fill",
    "source": "mapbox",
    "source-layer": ["water"],
    "paint": {
      "fill-color": "@water"
    }
```
``` json
{
    "id": "water",
    "type": "fill",
    "source": "mapbox",
    "paint": {
      "fill-color": "@water"
    },
    "filter": ["==", "$layer", "water"]
```
I just…the second makes me shudder a bit. Maybe that's just me though.

**Comment by jfirebaugh** [comment]
@lbud :+1:, let's keep it a separate property. We don't want to have to evaluate every filter on every feature.

**Comment by peterqliu** [comment]
cool. can this still be a string, or must be an array of one?

**Comment by nextstopsun** [comment]
@jfirebaugh Any progress on this issue? My use case is I need to create a hover effect on features from multiple layers. I like the approach of having a hidden layer with a filter that changes according to hovered feature id. But for now I've got to have a "hover" version of every layer instead of having just one hidden layer for all hovered ones.
BTW what is faster cpu-wise: setting a filter on a "hover" layer that uses the same source as a visible one, or just grabbing a geometry from hovered feature and pushing it to a geojson source for a hover layer?

**Comment by lucaswoj** [comment]
This hasn't come up in a long time. Closing as stale.
