### ISSUE TITLE
Stop functions based on arbitrary properties (not zoom)

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-style-spec#226]
Just capturing what has been discussed tonight — we need more fancy stops to be able to satisfy a use case such as choropleth maps (as a first step). Currently stops functions are always `[zoom, value]` pairs, while it would be nice to make stops based on arbitrary properties. Maybe like this:

```js
{
  "property": "height",
  "stops": [[0, "blue"], [100, "green"], [200, "red"]]
}
```

The next step would be calculating the breaks (0, 100, 200 above) automatically. For naive scales, we could do this either on the app side (generate manually) or as a style spec feature. But for something like [Jenks natural breaks](http://en.wikipedia.org/wiki/Jenks_natural_breaks_optimization), we need to know the whole range of values, which can only be calculated on the VT serving side if we don't want to readjust the classes as the tiles come.

cc @tmcw @jfirebaugh @edenh

**Comment by wboykinm** [comment]
:+1: for matching D3 scale syntax.

**Comment by jfirebaugh** [comment]
⇢ https://github.com/mapbox/mapbox-gl-style-spec/issues/249
