### ISSUE TITLE
Typed values

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-style-spec#227]
The types we're actually planning on implementing:

```
{ "type": "percent", "stops": [[0, 0], [20, 100]] }
```

```
{ "type": "color", "value": "#f00" }
```

```
{ "type": "constant", "value": "@foobar" }
```

The types:

| type | condition |
| ---- | --------- |
| percentage | must be 0 -> 1 |
| dimension | must be >0 |
| color | must be a valid color |
| constant | must be a valid constant name, which contains a valid value |
| degrees | must be a number |
| anchor | must be a position |
| font | must be a valid font |
| justify | must be a valid justification |

for instance, duration becomes a dimension, opacity is a percentage, all colors are colors, any 'enum', like 'anchor' deserves a type

we'll implement types everywhere: both in constants and in-place as style properties.

---

Having explicitly typed values for constants and properties will make interfacing with applications much easier. It is currently not possible to figure out if the following is meant for a number or an opacity:
```
{ "stops": [[0, 0], [20, 1]] }
```

It should look more like:
```
{ "type": "percent", "stops": [[0, 0], [20, 100]] }
```

Types would be `color`, `string`, `number`, `font`, `array`, `enum`, `percent`, `boolean`. Seeing three levels this could be applied:

#### 1. Constants only

Unlike the previous version, we should _not_ nest constants under a type name, because
that permits duplicate constant names: both a `@road` color and a `@road` width. That's confusing and
bad.

```
"constants": {
  "@road": { "type": "color", "value": "red" }
}
```

#### 2. Ramps only

```
"fill-opacity": { "type": "percent", "stops": [[0, 0], [20, 100]] }
"line-width":   { "type": "number", "stops": [[0, 1], [20, 24]] }
"text-color":   { "type": "color", "stops": [[0, "orange"], [20, "red"]] }
```

#### 3. All values everywhere typed

```
"@road":             { "type": "color", "value": "red" }
"@landcover-opacity: { "type": "percent", "stops": [[0, 0], [20, 100]] }
"line-width":        { "type": "number", "value": 3 }
"text-font":         { "type": "font", "value": "Open Sans Regular" }
```

This has the added bonus of further bulletproofing validation.

**Comment by tmcw** [comment]
The migration for this should type constants by their usage. Previously I looked into something like

```js

function guessConstantType(value) {
    if (typeof value === 'string') {
        if (csscolorparser.parseCSSColor(value)) {
            return 'color';
        } else if (value.indexOf('{') !== -1 && value.indexOf('}') !== -1) {
            return 'field';
        } else if (value.indexOf(',')) {
            return 'fontstack';
        }
    } else if (typeof value === 'number') {
        if (value >= 0 && value <= 1) {
            return 'opacity';
        } else if (value >= 0) {
            return 'dimension';
        }
    }
}
```

But realized it's better to use context than guess.
