### ISSUE TITLE
Decoupling styling structure from source structure

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-spec#231]
I'm not sure of the technical/performance implications here, but I would like to select data in multiple sources and source-layers, within one stylesheet layer.

The simplest example: Bridges and roads are nearly always styled identically, but Mapbox Streets separates them into separate `bridge` and `road` source layers.  This means separate layers in the stylesheet, because **the data lives on separate layers of the source**. A typical map with six types of roads --each with both bridge and surface sections, *and* each their respective casings-- currently requires 24 layers instead of 12, if we could combine bridges with roads.  

Another example: say I'd like to do a simple male-female visualization of gender distribution. But it's a dataset aggregated over 10 years, so I'm uploading 10 sources in year-long chunks. This would take 20 layers (one per gender, times 10) to select and style all my data instead of 2, if I could lump across sources into two big cohorts.

Phrased more generally, **structure of the source imposes significantly on structure of styling, and I think they should be separate concerns**. This happens whenever you'd like to combine data from:

- Different sources, or
- Different source-layers of the same source

Maybe the answer is "composite your data appropriately, before uploading", and that would be fair. But my ideal, one-stop-shop  scenario would be importing my sources, throwing all the layers into a hamper, and grabbing what I need via filters, regardless of source origin. Sources and source-layers would become properties with which I can filter, instead of something mandatory to provide.

cc/ @tmcw @nickidlugash @edenh

**Comment by jfirebaugh** [comment]
In contrast to #224, I'm not really comfortable with this. A layer having exactly one source is a fairly important invariant for efficient tile download and geometry processing.

**Comment by jfirebaugh** [comment]
> I'm uploading 10 sources in year-long chunks.

This is the perfect use case for VT compositing. Use a single composited source that includes all 10 chunks. Then you can style with two layers _and_ make only one request per tile instead of 10.

Unfortunately we need to work out some issues in the VT parsing pipeline for this to be viable: https://github.com/mapbox/vector-tile-js/issues/18.

**Comment by jfirebaugh** [comment]
Closing; this is something that's fairly fundamental to our data model and unlikely to change.
