### ISSUE TITLE
don't permanently crossfade patterns

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-style-spec#236]
This is how patterns currently look:

z15
![screen shot 2015-01-21 at 2 00 45 pm](https://cloud.githubusercontent.com/assets/1421652/5842822/14ffc58c-a176-11e4-80d6-d63ef67ef737.png)

z15.5
![screen shot 2015-01-21 at 2 01 18 pm](https://cloud.githubusercontent.com/assets/1421652/5842824/150743de-a176-11e4-9370-1dab8aa002fd.png)

z16
![screen shot 2015-01-21 at 2 01 40 pm](https://cloud.githubusercontent.com/assets/1421652/5842826/150ecabe-a176-11e4-980a-42601880960a.png)

At fractional zooms, the pattern is permanently crossfaded. The waves in the z15.5 image aren't clear. 

**Would it be better to not permanently fade and just show one scale?**
For comparison, z15.5 without permanent crossfading looks like this:

![screen shot 2015-01-21 at 2 17 36 pm](https://cloud.githubusercontent.com/assets/1421652/5843135/5c294198-a178-11e4-852c-a2f394ca1256.png)

Whenever a zoom boundary is crossed (from 15.99 to 16) the scale resets to avoid infinitely scaling. We could use timed transitions to make those smooth.

@nickidlugash @edenh @peterqliu

**Comment by edenh** [comment]
It would be great if patterns were crossfaded the way labels are instead of making the fade relative to zoom level. For example, as soon as z > 2, start fading to the new pattern scale. If necessary, add the equivalent to `raster-fade` or use the global transition setting to control fade duration.

**Comment by nickidlugash** [comment]
This sounds good to me.

**Comment by peterqliu** [comment]
The one upside of zoom-based crossfading, is that any change to the pattern begins and ends with the user's explicit zooming action. The tradeoff with using time-based fading, is a split-second of pattern shifting **after** the user has finished zooming. If this transition is long it'll feel like a lag; if it's short, it'll feel like a very sudden jump.

**Comment by edenh** [comment]
> The tradeoff with using time-based fading, is a split-second of pattern shifting after the user has finished zooming.

Labels are faded as you hit specific zoom levels, not after.

**Comment by peterqliu** [comment]
ah, do we mean removing crossfading *entirely*, not just permanent crossfading after the zoom? I was imagining that pattern fading would occur during zoom in the current manner, but snap to the nearest scale when zoom ends.

**Comment by ansis** [comment]
>  I was imagining that pattern fading would occur during zoom in the current manner, but snap to the nearest scale when zoom ends.

I think this would be more distracting. What I meant was fading only during a timed transition after crossing a boundary where the scale is reset. For example:

start zooming
z13 - scale 1
z13.5 - scale ~1.5
z13.99 - scale ~1.99
z14 - start fading from scale 2 to 1
z14.5 - middle of fade from scale ~3 to 1.5
stop zooming
z14.5 - scale ~1.5 when fading ends maybe 150ms or whatever after hitting z14

**Comment by peterqliu** [comment]
@edenh explained it to me via chat as well :+1:  sounds good

**Comment by jfirebaugh** [comment]
Are there spec-side changes required for this or is it purely a renderer change?

**Comment by ansis** [comment]
No spec changes necessary. Implemented:
https://github.com/mapbox/mapbox-gl-js/pull/950
https://github.com/mapbox/mapbox-gl-native/pull/773
