### ISSUE TITLE
Remove "fill-outline-color"

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#240]
As discussed in #199 and #223.

`fill-outline-color` is currently used in the bright and outdoors styles. @nickidlugash, @peterqliu can you comment on the importance of the property in those styles and in general? Would it be ok to remove for v7 without an immediate replacement via a "polygon" type or "multiple types" feature?

**Comment by peterqliu** [comment]
:+1: causes no breaking changes for me. 

Looking forward to polygons

**Comment by nickidlugash** [comment]
@jfirebaugh For these styles (and styles based on Mapbox Streets in general), the two features that depend the most on `fill-outline-color` are water and buildings. For these features, having an outline option is pretty important. 

> Would it be ok to remove for v7 without an immediate replacement via a "polygon" type or "multiple types" feature?

How long do we think it'll take to implement either a replacement (or optimize the performance of drawing lines enough that creating a second GL layer for the outlines won't kill performance)? If this is something that we're definitely doing soon, we can remove outlines for v7. I will want to manually update the v7 styles though, so I can optimize the way they look sans outline.

**Comment by jfirebaugh** [comment]
We really should do this. `fill-outline-color` adds complex special cases to the renderer for very little value.

**Comment by nickidlugash** [comment]
@jfirebaugh we use `fill-outline-color` in our private styles and public styles for buildings and road polygons. If we decide to remove it, we'll need to coordinate a styles update with the spec update.

**Comment by mourner** [comment]
I was initially worried about performance implications of this, but it looks like the only massive layer we use it for is buildings, which only appear on z15+, which is very easy to render compared to heavier zooms like z11-13. So I'm 👍 on this.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4088
