### ISSUE TITLE
Functions for text letter-spacing, line-height, and max-width

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-gl-style-spec#241]
Often I want to increase the spacing of text along with the size as the viewer zooms into the map. It would be awesome to control these with a function like text-size. This would be particularly beneficial to the look of water body & landform labels.

**Comment by peterqliu** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/956

**Comment by jfirebaugh** [comment]
In v7.
