### ISSUE TITLE
Document APIs for class mutation

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-spec#242]
- [ ] .addClass()
- [ ] .removeClass()
- [ ] .hasClass()
- [ ] .setClasses()
- [ ] .getClasses()

**Comment by tmcw** [comment]
This should be in gl-js, right? This is the spec repository.

**Comment by tmcw** [comment]
Also they're documented over there: https://github.com/mapbox/mapbox-gl-js/blob/master/API.md#working-with-style-classes
