### ISSUE TITLE
Change default value of `text-max-width`

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#244]
The current default is `15ems`, which I find is generally too long for most labels:

![screen shot 2015-02-04 at 7 42 57 pm](https://cloud.githubusercontent.com/assets/5607844/6053701/c203a6a0-acb0-11e4-8cdc-d02615172be6.png)

Can we make this value smaller? I like `10ems`:

![screen shot 2015-02-04 at 7 43 09 pm](https://cloud.githubusercontent.com/assets/5607844/6053707/d274d720-acb0-11e4-857b-311b7a4a2069.png)

...but something like `12ems` would be fine too, if others think that `10ems` is too short.

**Comment by nickidlugash** [comment]
@tmcw @lbud can this be in v8?

**Comment by lbud** [comment]
@nickidlugash :+1: :ship: it

**Comment by nickidlugash** [comment]
Done via https://github.com/mapbox/mapbox-gl-style-spec/commit/ce6af7f49488f72e71ecfc1907aea6a0270fb178 and added to [v8 PR](https://github.com/mapbox/mapbox-gl-style-spec/pulls). Thanks for your help, @lbud!
