### ISSUE TITLE
Move `"constants"` keys in spec to directly above `"layers"`?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#246]
Can we reorder the keys in [the style spec](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v7.json) so that `"constants"` are directly above layers? This seems most human-readable to me for outputting json stylesheets.

If this seems okay to others, I'll make the change. Would this be done in the [`"constants"` object within the `"$root"` object](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v7.json#L16) (as opposed to the [top-level `"constants"` object](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v7.json#L44))?

**Comment by jfirebaugh** [comment]
Sounds good to me.

> Would this be done in the "constants" object within the "$root" object

Correct.
