### ISSUE TITLE
centerpoint

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-style-spec#247]
Style objects should have a `center` key. This could be optional. If it were to follow the pattern used by the Mapbox Map API, would look like:

```
"center": [ 
  {longitude}, 
  {latitude},
  {center},
  {bearing}
]
```

**Comment by jfirebaugh** [comment]
They should be separate properties, identical to [gl-js map options](https://www.mapbox.com/mapbox-gl-js/api/) `"center"`, `"zoom"`, and `"bearing"`.

**Comment by incanus** [comment]
These would be great, and I agree with @jfirebaugh. Bearing! Rad.

**Comment by samanpwbb** [comment]
@jfirebaugh sounds good! Anything I can do to help make this happen?

**Comment by jfirebaugh** [comment]
PRs for style-spec, js, and native. :)

**Comment by tmcw** [comment]
Does this actually require integration with gl-js and gl-native? I don't really think it should, at this point.

**Comment by incanus** [comment]
We load TileJSON, and in the iOS tools, we use that to inform initial setup of the map. I could see GL styles eventually working this way, where all of the setup info is encapsulated in the style itself, so that it completely sets an environment state.

**Comment by tmcw** [comment]
Implemented in the v8 omnibus. Open to eventual implementation but don't think it should block merge.
