### ISSUE TITLE
add "metadata" property at top level and within layers

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#251]
This would be a space to store arbitrary properties, either user-specified or for tools such as the editor. Metadata stored by tools should always use a key prefix such as `"mapbox:"` to avoid collisions with user data.

Once this is in the spec and existing tooling / styles are converted, update mapbox-gl-style-lint to prohibit unknown top-level and layer properties.

**Comment by scothis** [comment]
:+1:

**Comment by jfirebaugh** [comment]
Fixed in #314.
