### ISSUE TITLE
multiple label positions

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-style-spec#253]
Right now you can only specify one possible position for a label. It would be great if it could try a second position if it doesn't fit in the first.

How would this look in the style spec?
Does the carto approach work well?

If I'm understanding carto correctly:
When `text-placement-type` is `simple` and a string of positions like `N,S,E,NW` is provided, then dx and dy are multiplied based on the position (-1 for W, 1 for E, 0 otherwise). The position also affects justification and alignment.

@nickidlugash @ajashton @peterqliu

**Comment by ansis** [comment]
@ajashton: @nickidlugash said that `text-placement-type: simple` is used rarely in styles. Instead, a position `ldir` is somehow predetermined and stored in the feature's properties. Why is that used instead of the built in support in mapnik?

**Comment by ajashton** [comment]
@ansis If one label needs to be rendered across multiple tiles, there is no way to ensure that the same final position is reached when multiple positions are tried since each tile is rendered independently. You end up with cut-off labels or duplicate labels all over the place.

**Comment by ansis** [comment]
Thanks, that makes sense.

> I assume this is less of a problem for GL / client-side rendering in general.

It is a problem right now because we're trying to make labeling work identically in client-side rendered maps and in fallback versions. We may want to change this though. GL support might be high enough that it's ok if fallback tiles have slightly worse labels.

**Comment by alinapaz** [comment]
@ansis got a related request from [Rentpath](https://github.com/mapbox/support/issues/339). Are multiple or dynamic labels in our roadmap?

>
Hey Angelina,
Does mapbox support or plan to support dynamic label placement? eg force based. Then two markers next to each other can have labels on opposing sides.
Thanks,
Caleb

**Comment by lucaswoj** [comment]
Closing as stale
