### ISSUE TITLE
Implement transitions for all (or more) piecewise functions?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#254]
ref https://github.com/mapbox/mapbox-gl-js/pull/976#issuecomment-72782711

If I'm understanding correctly,  `*-image` and `line-dasharray` are currently the only piecewise functions that have timed transitions implemented. Is it possible to implement this for all (or more) piecewise functions, e.g. `text-transform`? Are there restrictions on what is possible to crossfade?

/cc @ansis @jfirebaugh

**Comment by ansis** [comment]
`text-transform` and others are layout properties which makes makes them harder to crossfade (we'd have to do them differently at least). It isn't possible right now, but maybe later.

What is an example where you would want this?

**Comment by jfirebaugh** [comment]
Closing -- I think it's unlikely we'd do this due to the technically difficulty and possibility of conflicting with making the properties data-driven.
