### ISSUE TITLE
get rid of `text-max-size` and `icon-max-size`

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-style-spec#255]
currently
`text-max-size` is a layout property and is used for label placement
`text-size` is a paint property is used to change

We should only have one property.

How would we deal with a property that is need both for layout and rendering?

**Comment by jfirebaugh** [comment]
layout could calculate what the actual maximum `text-size` is going to be, right?

**Comment by mourner** [comment]
Yeah, the only problem is that we introduce a new concept here: a paint property that implicitly affects the layout step as well. But it's probably fine.

**Comment by jfirebaugh** [comment]
Hrm, yeah, `setPaintProperty` would then have to special-case `text-size` to trigger a relayout.

**Comment by mourner** [comment]
Or we could have it the other way around — make it a layout property that implicitly creates a paint property.

**Comment by jfirebaugh** [comment]
It would still need to support interpolated functions, which would be a different special case. But maybe a less problematic one.

**Comment by nickidlugash** [comment]
@jfirebaugh @mourner @ansis any consensus on what we should do here?

**Comment by nickidlugash** [comment]
I added this to [v8 omnibus](https://github.com/mapbox/mapbox-gl-style-spec/pull/264).

**Comment by nickidlugash** [comment]
We should also get rid of `icon-max-size`. I've added that to this ticket name, and will add to v8.

**Comment by jfirebaugh** [comment]
@ansis, can you look into this when you get back?

**Comment by ansis** [comment]
pull request for -js: https://github.com/mapbox/mapbox-gl-js/pull/1419

Is the rest of v8 implemented in -native?
