### ISSUE TITLE
Font stacks should be arrays

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#257]
Font stacks shouldn't be strings concatenated by `,`s: this makes constants of fontstacks weird. Fontstacks should be string arrays.

**Comment by ansis** [comment]
:+1:

**Comment by jfirebaugh** [comment]
:+1:

**Comment by mikemorris** [comment]
:+1:

**Comment by tmcw** [comment]
Going to merge in the linter first, waiting on slow slow mr travis https://github.com/mapbox/mapbox-gl-style-spec/pull/258
