### ISSUE TITLE
SVG support for gl-style-spritify

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-spec#267]
Existing icon sets are often found as handy loose PNGs, but custom-designed icons often start in vector format, usually SVG. I'd like `gl-style-spritify` to:

1) accept SVG's as inputs, to be made into a single PNG sprite sheet
2) have an option to produce both regular and retina assets from the same SVG

cc @jfirebaugh

**Comment by jfirebaugh** [comment]
This would require a high-quality SVG rasterizer that we can pull in as a node module, which is a tall order.

**Comment by samanpwbb** [comment]
Spritezero does this: https://github.com/mapbox/spritezero
