### ISSUE TITLE
Array default value

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#268]
Is the default value for a dashArray `[1,0]`? Let's enforce this in the spec if so.

**Comment by ansis** [comment]
I think something like `none` makes more sense than `[1, 0]`. We already use `undefined` for `none` for properties like  fill-image, line-image, text-field, icon-image.

Are `undefined` default values causing problems somewhere?

**Comment by samanpwbb** [comment]
from https://github.com/mapbox/mapbox-gl-style-spec/issues/351#issuecomment-134408898

> the "default" is "no dashes", meaning if you don't want dashes, don't include this pattern in the style at all.

This reasoning does make sense and we're handling undefined default values okay upstream now.
