### ISSUE TITLE
Add a per-layer opacity property

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#273]
Background: https://github.com/mapbox/mapbox-gl-js/issues/859#issuecomment-65845587

Is this currently possible for JS/native to render (or will it ever be)?

Useful for layers that are designed to have overlapping geometries, such as all the layers in Mapbox Terrain.

**Comment by nickidlugash** [comment]
It looks like the current opacity properties have switched to per-geometry. So I guess the new question is: can we add a per-layer opacity property? Useful for tunnels on basemaps:

![screen shot 2015-03-31 at 5 33 36 pm](https://cloud.githubusercontent.com/assets/5607844/6929847/1ed3decc-d7cc-11e4-85ea-682e2557b4f9.png)

@samanpwbb @ajashton Any thoughts?

@ansis @kkaefer is this feasible?

**Comment by samanpwbb** [comment]
What if setting RGBA fill/stroke was per-feature while setting Opacity was per layer? 

Both per-feature and per-layer are important, but if I had to pick one I'd pick per-layer (to avoid the kinds of problems you can see in the screenshot above).

**Comment by nickidlugash** [comment]
> What if setting RGBA fill/stroke was per-feature while setting Opacity was per layer?

This seems like a good idea for me. I don't currently tend to use a lot of RGBA values, but this might make more sense than implementing two different opacity properties for each layer type.

**Comment by nickidlugash** [comment]
> Per-layer and per-feature alpha values are hard to implement; a per-layer alpha value means that we'd have to render to a buffer first, then composite onto the main framebuffer.

@kkaefer does this mean that having a per-layer opacity property would take a lot of time/energy but is doable, or that it's something you don't think we should consider doing at all?

**Comment by ansis** [comment]
We could implement per-layer alpha by just using the depth buffer to prevent double drawing. We would have to draw lines with two calls so that we can draw the solid part first and the antialiasing second. It wouldn't be exactly the same as carto if you have both per-layer and feature-level opacity, but this case doesn't seem that important.

**Comment by jfirebaugh** [comment]
Can someone define what "per-layer" opacity means precisely? Or with an example? E.g. if you have a layer with a red triangle at 50% opacity on top of a blue square at 50% opacity, with a "layer opacity" of 50%, how is that supposed to render?

**Comment by nickidlugash** [comment]
@jfirebaugh I think like this (although I'm not sure I'm rendering @ansis's suggestion correctly):

![screen shot 2016-06-28 at 11 25 49 am](https://cloud.githubusercontent.com/assets/5607844/16421495/25a3f698-3d23-11e6-965b-2fe82a9ab5f3.png)

/cc @samanpwbb

**Comment by samanpwbb** [comment]
Yep, what @nickidlugash said. I would expect the cartoCSS behavior rather than Ansis's suggested implementation in cases where there is both per-layer and per-feature opacity. Here's an example with strokes that illustrates how per-layer opacity might be preferable:

![screen shot 2016-06-28 at 11 32 59 am](https://cloud.githubusercontent.com/assets/108094/16421804/2a27a59c-3d24-11e6-8ff4-a775ad579f92.png)

**Comment by jfirebaugh** [comment]
Thank you, those examples are great.

I believe the annotations here are correct:

![image](https://cloud.githubusercontent.com/assets/98601/16423294/53888352-3d10-11e6-8cd9-680e02094693.png)

The cartoCSS behavior is the one that requires composited rendering (rendering the layer first to a buffer, then compositing that layer with the scene using the layer-wide opacity).

**Comment by ajashton** [comment]
Normally it's not really necessary to have both per-object and per-layer opacity on the same layer, just one or the other. So if we can't fully replicate the Mapnik behavior then that's fine, just these two are key:

![screenshot-2016-06-28-12 23 15](https://cloud.githubusercontent.com/assets/126952/16423800/8658eae0-3d2b-11e6-8eef-0a8eb36f1355.png)

**Comment by jfirebaugh** [comment]
With data-driven styling it's already possible to set a different fill-color rgba value for each feature. So it's pretty awkward to prohibit per-feature opacity.

**Comment by ezheidtmann** [comment]
It looks like this is now implemented for `fill` layers via the `fill-opacity` paint property. Is there any way to do this for `line` layers? The `line-opacity` property seems to set a per-geometry opacity, at least in js v0.23.0.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4090
