### ISSUE TITLE
layout property for sorting symbols

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-style-spec#274]
We need some property to control whether symbols are sorted so that we can implement https://github.com/mapbox/mapbox-gl-native/issues/988.

With the new labeling this is easy to implement: https://github.com/mapbox/mapbox-gl-js/commit/5bf094f7c26ebe2730f258b2ac5cef1ca804767d

Do we want to support sorting in any direction?

The property could be a

#### angle
`"symbol-sort": 0` would sort bottom-up and `"symbol-sort": 90` would sort left-to-right

#### enum
`"symbol-sort": "y-ascending"` or something

#### boolean
`"symbol-sort-y": true`

**Comment by jfirebaugh** [comment]
Is a style property necessary? What if symbols always sort top to bottom relative to the viewport?

**Comment by ansis** [comment]
Always sorting sounds good to me.

Should sorting only affect draw order and not placement order?
