### ISSUE TITLE
Feature density driven visibility 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#275]
Total blue sky idea related to https://github.com/mapbox/mapbox-gl-styles/issues/94

A good map design shows neither too few nor to many features. Users should never be looking at a large blank area which actually has features at higher zoom levels, nor should they see a cluttered map, with too many features to be useful / beautiful.

To this end, map designers are faced with some tough compromises. They cannot afford to display `class=street` ways at, say, z12 in dense suburban areas because the map would be too cluttered (and these streets aren't particularly important landmarks anyway). But in rural areas, where there are many `class=street` ways which _are_ important landmarks, it might make sense to display them much earlier. 

![32170332-dec1-11e4-8dcb-caf5056d8ad0](https://cloud.githubusercontent.com/assets/281306/7079128/be0fd684-deee-11e4-87b3-8bac2ff0bcae.png)

The gold standard here would be defining styles based on feature density.

Imagine if the top level stylesheet object had a property like `feature-desnity: {number}`, which would define the desired # of features in one unit area of the map. 

Then, each layer would define a `feature-importance: {number}` property which would specify its importance relative to other layers. By default, `feature-importance: 0` would always be rendered (which allows for nice backwards compatibility). Next, we would check if we could render all layers of `feature-importance: 1` while maintaining our desired `feature-density`. If so, we do render all features of `feature-importance: 1`. Then, we consider `feature-importance: 2`, and so on. 

In effect, this would show as many features as possible on every zoom level in every context without making the map ever appear too overwhelming or too sparse. I can't be certain, but I think Google Maps does some version of this statically (i.e. when constructing the data tiles). It would also free us from having to write complex zoom level filters for every map, through trial and error. 

I don't know what the performance impact of of this would be. We can precompute a lot of information, with some knowledge of the data and the stylesheet. 

cc @nickidlugash

**Comment by yhahn** [comment]
@lucaswoj curious what you're thinking here in terms of implementation -- the tricky part of implementing this to me seems to be making it parallelizable/seamless across tile boundaries and deterministic:

    .... ....
    .... ....
    ____ ....
    .... ....

*some road disappearing across tile boundaries because one is loaded later and calculates its feature density without knowledge of what surrounding tiles kept.*

Totally uninformed opinion from my gut is that this may be better done (but probably equally as challenging) when constructing our vector tiles.

**Comment by lucaswoj** [comment]
Definitely agree with everything you're saying. This is a high level feature request coupled with the simplest implementation I could think of (but not a great one). 

My intention was that layers would be shown / hidden across all visible tiles, perhaps forcing us to rerender some tiles as a user pans from
a less dense to a more dense area. 

If we can envision a way to do this entirely or partially at tile-construction time, that would ideal. Maybe this feature could live in the data importing mode in GL studio?

Also, it doesn't have to be visibility by layer, showing / hiding individual features might be more seamless, assuming we could make that seamless across tiles.
