### ISSUE TITLE
Circle render type

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#276]
It looks like this was [implemented in the past](https://github.com/mapbox/mapbox-gl-style-spec/pull/127) and then removed. There's [a discussion that mentions it](https://github.com/mapbox/mapbox-gl-style-spec/issues/67) but no real connecting-the-dots as far as whether and how this would be implemented.

My vote: circles of customizable radius and color are essential for basic data visualization.

**Comment by jfirebaugh** [comment]
https://github.com/mapbox/mapbox-gl-style-spec/pull/68 has the main discussion.

**Comment by tmcw** [comment]
I disagree with the main discussion and feel strongly that we should implement a circle type.

* Scaled icon circles are not a replacement for absolutely sized generated circles. What the user wants is "a 5px circle", not "choose an sdf sprite, guess what size it is, scale it by 5/14"
* Circle type increases similarity to Leaflet, OpenLayers, and virtually every other map framework
* Having a circle in a sprite to draw circles is an inconvenience: scaled circles are one of the main things that people will add via the JavaScript API, and at that point the choice of sprite is mostly baked-in.

**Comment by mourner** [comment]
Well, to reiterate what I said in the #68 discussion, I'm fully in support of a dedicated circle type and agree with Tom.

**Comment by incanus** [comment]
We need a circle primitive for iOS as well, for things like https://www.mapbox.com/mapbox-ios-sdk/examples/drawing-circle/ — note the runtime color, opacity, and stroke settings.

**Comment by jfirebaugh** [comment]
Included in v8.
