### ISSUE TITLE
Use "GL_LINES" to render thin (< 1 px) lines

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-style-spec#279]
We're frequently drawing thin lines (< 1 px) with the regular line tesselator, which produces many triangles, while we could just use something like the outline shader to draw the lines much faster.

I'm not sure what the best way to implement this is. We could either detect in the renderer, whether a certain layer will never go over a certain threshold, or we could make it more explicit by adding a `layout` property that'll mark the layer as a simple line/outline/fast line so we don't have to autodetect whether we can use the fast path.

/cc @tmcw @ansis

**Comment by ansis** [comment]
First we should benchmark and see if it's actually faster to render.

Why do you think GL_LINES would be faster? half as many vertices?

**Comment by lucaswoj** [comment]
Closing as stale

**Comment by lucaswoj** [comment]
Actually, this might be valuable in conjunction with #240

**Comment by jfirebaugh** [comment]
Closing -- we've had lots of problems with GL_LINES. Best avoided.
