### ISSUE TITLE
arc from point, radius and start/stop angle

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-style-spec#283]
I would like to draw an arc (A portion of the circumference of a circle) with Mapbox GL based on a center point, start/stop angle (either on screen or true-north (does not matter)) and radius (in points, not meter on the ground). To top it all, the arc should be stylable with color and opacity like a Line.

There should probably be something like an arc-rotation-alignment as well. For my project, I would align the arc to "map".

My motivation for this is to be able to draw lighthouse sectors for a nautical chart.
![screen shot 2015-05-11 at 10 46 30](https://cloud.githubusercontent.com/assets/445229/7561272/14a80a44-f7cb-11e4-8651-38b9f0fe2c54.png)

A workaround could be to draw this on the server and use it as a Symbol, but a true GL variant would be nicer.

Any tips to where I should start digging?

**Comment by incanus** [comment]
https://github.com/mapbox/mapbox-gl-style-spec/issues/276 is probably a good base for this. We may look into the circle primitive in the next iOS beta when we hit shape annotations, so this will be getting some attention soon.

**Comment by lucaswoj** [comment]
"fill" layers are a good fit for this use case.
