### ISSUE TITLE
Remove `symbol-avoid-edges`?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#287]
@ansis you mentioned that you thought we should consider removing `symbol-avoid-edges` and just automating the value in the renderer. If I'm understanding correctly, the two main use cases for `symbol-avoid-edges: true` are:
1. For symbol layers in styles that use data sources with no/insufficient buffers.
2. For point symbol layer placed after a line symbol layer.

Is there a way to figure out when case 1. exists? Whether the buffers are large enough depends on both how big the buffers are and how big the labels are, right?

I'm guessing that automating 2. is pretty straightforward?

/cc @mayagao @samanpwbb

**Comment by lucaswoj** [comment]
I don't think there's any way to detect case 1. 😞 

Closing this for now as we cannot detect all cases where this setting might need to be enabled.
