### ISSUE TITLE
Circle types should be translatable

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-style-spec#291]
While implementing circle support for https://github.com/mapbox/mapbox-gl-native, I've noticed that we're missing `circle-translate` style on the spec. Part of https://github.com/mapbox/mapbox-gl-native/issues/1740.

@tmcw @kkaefer @tmpsantos @mourner @ansis

**Comment by lucaswoj** [comment]
GL JS side is all done!
