### ISSUE TITLE
Duplicate "circle" type in v8.json

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-style-spec#297]
The `circle` type is mentioned twice in https://github.com/mapbox/mapbox-gl-style-spec/blob/v8/reference/v8.json#L205 and https://github.com/mapbox/mapbox-gl-style-spec/blob/v8/reference/v8.json#L207.

Same for `layout_circle` in https://github.com/mapbox/mapbox-gl-style-spec/blob/v8/reference/v8.json#L262 and https://github.com/mapbox/mapbox-gl-style-spec/blob/v8/reference/v8.json#L265.

Part of https://github.com/mapbox/mapbox-gl-native/issues/1740.

@tmcw @kkaefer @tmpsantos  :-)

**Comment by jfirebaugh** [comment]
Fixed in bbd7e37b2c19df86386b585d545850ad3c91dc9e.
