### ISSUE TITLE
validate presence of glyphs/sprite when text/icons are used

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#299]
Validation should catch an issue like https://github.com/mapbox/mapbox-gl-js/issues/1291.

**Comment by jfirebaugh** [comment]
Also validate that the glyphs url includes `{fontstack}` and `{range}`.

**Comment by bhousel** [comment]
Hmm what about #170

**Comment by jfirebaugh** [comment]
Fixing this would also fix #170, in that it would codify that the answer is "sometimes" and enforce it.
