### ISSUE TITLE
adjust how interval functions are migrated v7 ⇢ v8

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#307]
v7 piecewise-constant functions have the same number of values in their domain and range. If a given input value is less than both the first and second domain value, the result is the first range value. This means the first domain value is effectively unused.

Currently, v7 piecewise-constant functions are migrated to v8 interval functions by duplicating the first range value. Instead, they should be migrated by dropping the first domain value.

cc @lucaswoj

**Comment by lucaswoj** [comment]
:+1:
