### ISSUE TITLE
Why can't a filter be in a ref layer?

### ISSUE THREAD

**Issue by Schwanksta** [mapbox/mapbox-gl-style-spec#316]
Essentially I'd like to set up base style and alter the paint based on a property.

I figured I could set up a layer and use ref to create styles that inherit a base, kinda like Carto, where I can say

```css
marker-allow-overlap: true;
marker-ignore-placement: true;
marker-fill: #000;
[day="MON"] { marker-fill: @mon }
[day="TUE"] { marker-fill: @tue }
...
```

So I tried this:

```json
{
    "id": "signs",
    "type": "symbol",
    "source": "broom-signs",
    "source-layer": "data",
    "layout": {
      "icon-allow-overlap": true,
      "icon-ignore-placement": true,
      "icon-image": "circle.sdf"
    },
    "paint": {
        "icon-size":0.3,
        "icon-color": "#000"
    }
},
{
    "id": "mon-signs",
    "filter": ["==", "day", "MON"],
    "ref": "signs",
    "paint": {
        "icon-size":0.3,
        "icon-color": "@mon"
    }
}
```

However, I get `"filter" is prohibited for ref layers`. 

Is there a way of accomplish this without setting up a full layer for each filter? Would filtering in a ref layer be possible?

Right now I'm going with just writing a loop to do it for me:

```javascript
_.each(['mon', 'tue', 'wed', 'thur', 'fri'], function(day) {
    style.layers.push({
        "id": day + "-signs",
        "type": "symbol",
        "source": "broom-signs",
        "source-layer": "data",
        "filter": ["==", "day", day.toUpperCase()],
        "layout": {
          "icon-allow-overlap": true,
          "icon-ignore-placement": true,
          "icon-image": "circle.sdf"
        },
        "paint": {
            "icon-size":0.3,
            "icon-color": "@" + day
        }
    });
});
```

Thanks

**Comment by peterqliu** [comment]
No, a ref layer necessarily inherits the filter of its referent; its purpose is less for ease of authoring, than rendering optimization. If you'd like to have a different marker for each day, you will need a new layer per day with its own filter, and own marker-fill color.

**Comment by Schwanksta** [comment]
That's what I assumed. Appreciate the response.
