### ISSUE TITLE
icon-rotate and feature field

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [mapbox/mapbox-gl-style-spec#320]
Is there a way to use a numerical value via a field property to rotate a symbol using "icon-rotate"?  Maybe something similar to  "text-field": "{MY_FIELD}" to populate text values for icons.

**Comment by jfirebaugh** [comment]
Not currently. This falls into the category of "data-driven styling" -- see #249.

**Comment by wheredoesyourmindgo** [comment]
Thanks @jfirebaugh.  If anyone is looking for a whacky work-around for this I've been just using imagemagick to generate 360 rotated versions of the same symbol, and stuffing those into a sprite sheet using gl-style-spritify from [mapbox-gl-style-spec](https://github.com/mapbox/mapbox-gl-style-spec).  At that point you can simply use icon-image layer definition suffixed with the relevant token.

**Comment by jiggy1com** [comment]
@wheredoesyourmindgo I think for now I'm going to have to use your solution

**Comment by EwenH** [comment]
Thanks @wheredoesyourmindgo - This is so much work for a small item (I want to show the wind direction) however your process sounds logical. 

I shall be some time...
