### ISSUE TITLE
Allow use of find/replace regex to compute property values

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#321]
Currently we can't make use of the way duplex shields in the mapbox streets data are [designed to be styled](https://github.com/mapbox/mapbox-studio-streets.tm2/blob/master/label.mss#L492), because we can't use regex as part of values, and we also don't accept `\n` as a space for line wrapping. Is it feasible to implement the ability to use find/replace and `\n`?

**Comment by 1ec5** [comment]
The regex half of this is covered by #233.

**Comment by jfirebaugh** [comment]
#233 is for the use of regexes in [filters](https://www.mapbox.com/mapbox-gl-style-spec/#filter), which is a different use case.

I seem to recall an issue for wrapping on newlines, but I can't find it at the moment.

**Comment by lucaswoj** [comment]
We have a separate issue for regex support and have already implemented newline support.

**Comment by jfirebaugh** [comment]
As noted above: the other issue is for regex support in filters. This is about regex support in functions.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4100
