### ISSUE TITLE
Prohibit unknown top-level and layer properties

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#325]
Followup to #251 / #314.

**Comment by jfirebaugh** [comment]
As noted in https://github.com/mapbox/mapbox-gl-style-spec/pull/558, I think we've lost our window to do this safely for v8 -- prohibiting unknown top-level and layer properties now is likely to break styles in the wild. Targeting for v9.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4094
