### ISSUE TITLE
Support gradient-colored shapes

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#349]
It would be useful to support gradient-colored lines, fills, and backgrounds. What would the stylesheet syntax look like? How would this work with data-driven styling?

ref https://github.com/mapbox/mapbox-gl-native/issues/2142

cc @webventil

![](https://cloud.githubusercontent.com/assets/1701915/9403260/b7a7eb82-47e5-11e5-84b6-7550d4c15edc.png)

**Comment by jfirebaugh** [comment]
See also https://github.com/mapbox/mapbox-gl-js/issues/748.

**Comment by tmcw** [comment]
I think the style spec side here is totally doable but the hard part is going to be data representation: GeoJSON and lots of other formats are derived at a basic level from the [Simple Features Spec](http://www.opengeospatial.org/standards/sfs), which, in its definition of 'simple' does not include the concept of values differing _along_ lines, which is how I'd assume you would want to control the color of the line.

The GPX and OSM formats do support this, and I have a [proposal for an add-on spec for GeoJSON](https://github.com/mapbox/geojson-coordinate-properties). Vector tiles, as far as I know, don't support values along lines.

**Comment by tomtaylor** [comment]
While this is being considered, it would also be useful to be able to have polylines where the dashing varies along the line too. So you can make certain sections as dotted, for example.

**Comment by jordi-adame** [comment]
+1

**Comment by cowgp** [comment]
+1

**Comment by isimonescu** [comment]
Any progress on this?

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4095
