### ISSUE TITLE
Every property should have a default value in the spec

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-style-spec#351]
We are running into issues where we need to fallback to a default value in the UI, but the spec doesn't have anything defined -> 

icon-image: https://github.com/mapbox/mapbox-gl-style-spec/blob/fe768eb9e73b8cf8bd934297f9813cadacb6b0a1/reference/v8.json#L444-L449

fill-outline-color: https://github.com/mapbox/mapbox-gl-style-spec/blob/fe768eb9e73b8cf8bd934297f9813cadacb6b0a1/reference/v8.json#L836

fill-pattern: https://github.com/mapbox/mapbox-gl-style-spec/blob/fe768eb9e73b8cf8bd934297f9813cadacb6b0a1/reference/v8.json#L876-L882

line-dasharray and line-pattern: https://github.com/mapbox/mapbox-gl-style-spec/blob/fe768eb9e73b8cf8bd934297f9813cadacb6b0a1/reference/v8.json#L958-L978

background-pattern: https://github.com/mapbox/mapbox-gl-style-spec/blob/fe768eb9e73b8cf8bd934297f9813cadacb6b0a1/reference/v8.json#L1288-L1293

**Comment by jfirebaugh** [comment]
There is no appropriate value (that can be expressed in JSON) for these properties.

* icon-image, fill-pattern, line-pattern, background-pattern: the "default" is "no image", meaning if you don't want an image/pattern, don't include this property in the style at all.
* fill-outline-color: the default is "same as the fill-color"
* line-dasharray: the "default" is "no dashes", meaning if you don't want dashes, don't include this pattern in the style at all.

**Comment by samanpwbb** [comment]
That makes sense, I'll work around it on my end.
