### ISSUE TITLE
gl-style-spritify generates empty sprites from Mapbox GL Example Styles

### ISSUE THREAD

**Issue by StepanKuzmin** [mapbox/mapbox-gl-style-spec#354]
Hi! I've tried to generate sprites from [Mapbox GL Example Styles](https://github.com/mapbox/mapbox-gl-styles/tree/98413a8bb4840d4c04387600967b787a15790569) using gl-style-spritify.

```shell
> npm install -g mapbox-gl-style-spec
> git clone https://github.com/mapbox/mapbox-gl-styles
> cd mapbox-gl-styles
> gl-style-spritify bright sprites/bright-v8/_svg
> du -sh bright*

4.0K	bright.json
  0B	bright.png
4.0K	bright@2x.json
  0B	bright@2x.png
```

So *.png are all empty, and *.json contains only `{}`.

**Comment by StepanKuzmin** [comment]
I've to mention, that there was `generate_sprites.js` script, wich was using `spritezero` (and it works well with Mapbox GL Example Styles). But gl-style-spritify uses `spritesmith`, as I see. So what am I missing?

**Comment by tmcw** [comment]
Yep, we should publish a command in `spritezero` that does this. GL Style Spec should drop the sprite generation, as far as I see it.

**Comment by tmcw** [comment]
Okay: spritezero cli https://github.com/mapbox/spritezero-cli

Next action on this ticket is to remove the sprite generation here and point to spritezero-cli in the docs.
