### ISSUE TITLE
rename source to dataset

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#357]
"Dataset" is the terminology we are using elsewhere in the Mapbox ecosystem. Thus:

* `sources` ⇢ `datasets`
* `source` ⇢ `dataset`
* `source-layer` ⇢ `dataset-layer`

**Comment by lyzidiamond** [comment]
@jfirebaugh how can I help here?

**Comment by jfirebaugh** [comment]
@lyzidiamond Use "dataset" consistently throughout documentation and examples. We'll do the spec property renames in the next spec version.

**Comment by willwhite** [comment]
Slight adjustment here. Looks like we are going `sources` -> `tilesets`.

https://github.com/mapbox/studio/issues/2060

**Comment by jfirebaugh** [comment]
I later realized that this wouldn't be a good idea, because tilesets are not the only type of source: there are also GeoJSON, Image, and Video sources. We need a term that encompasses all the things where data can come from, and "source" is as good as any.
