### ISSUE TITLE
Support for icons at the end of lines

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-spec#359]
It would be useful to tack a sprite onto each end of lines, especially for arrowheads. Each should be rotationally aligned to the orientation of the line's end.

Optionally, support two different images for each end of the line.

The analogous feature in Illustrator:

<img width="223" alt="screen shot 2015-09-16 at 6 02 54 pm" src="https://cloud.githubusercontent.com/assets/4551508/9922413/0691ec4a-5c9d-11e5-89f7-58012539003f.png">

**Comment by ajashton** [comment]
Bridges!

<img src="https://cloud.githubusercontent.com/assets/126952/22083106/9398c33e-dd98-11e6-8c25-ed56934f1bb3.png" width="287" />

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4096
