### ISSUE TITLE
Document glyphs 

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#361]
This ticket is the `glyphs` equivalent of #315. See https://www.mapbox.com/mapbox-gl-style-spec/#sprite for how we document sprites.

Relevant questions to answer:
- What's the glyph pbf format?
- What's the algorithm for filling in the `{range}` template parameter?
- What's the algorithm for filling in the `{fontstack}` template parameter?

The answers to these question implicitly define what a glyphs API server needs to be capable of.

**Comment by gertcuykens** [comment]
Can this get a slightly higher priority? I assume many users have no clew including me what range and fontstack means https://www.mapbox.com/mapbox-gl-style-spec/#glyphs Also I can't find any correlation with https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-font to figure out what fonts I can use?

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4097
