### ISSUE TITLE
how to filter for feature that does not have field

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-style-spec#364]
How do I write a filter to show all features that do not have a particular field?

Something like this doesn't work:

```
["!in", "class", ""]
```

And 
```
["in", "class", null]
```

results in an invalid stylesheet.

**Comment by tmcw** [comment]
I would like to propose `has` and `!has` as operators:

    ["has", "class"]
    ["!has", "class"]

**Comment by jfirebaugh** [comment]
:+1: to adding `has` and `!has`.

**Comment by jfirebaugh** [comment]
We did this.
