### ISSUE TITLE
render bug with background-pattern

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-style-spec#365]
@adam-mapbox and I are working on an unrelated issue and trying to use `background-pattern` to debug. However we are seeing some really weird behavior. 

We changed Streets from a solid color to use an existing sprite in the sheet (this happens with this power-of-two texture, but also with those that are not): 

```diff
diff --git a/styles/streets-v8.json b/styles/streets-v8.json
index 53b9027..992b4d7 100644
--- a/styles/streets-v8.json
+++ b/styles/streets-v8.json
@@ -20,7 +20,7 @@
        "visibility": "visible"
      },
      "paint": {
-        "background-color": "#ede9d9 "
+    "background-pattern": "marsh-32"
      }
    },
    {
```

However it seems to break the `line` and `fill` primitives — only symbols like annotations, shields, and text glyphs seem to render above the background! 

![screen_shot_2015-09-29_at_4 35 35_pm](https://cloud.githubusercontent.com/assets/17722/10181089/8e13c67c-66c8-11e5-9027-4e685f380838.png)

The background image also doesn't pan? Should it? 

Are we doing something wrong, or is this possibly a bug? If a bug, we can flag in `mapbox-gl-native`. 

/cc @kkaefer

**Comment by incanus** [comment]
Summarizing chat: 

- This does appear to be a bug, at least in native. 
- We do want to keep this feature. 
- We should see if it exists in JS. 
- We should move work to ticket(s) in those repos as necessary.

**Comment by jfirebaugh** [comment]
Looks like https://github.com/mapbox/mapbox-gl-native/issues/774.

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/pull/2527
