### ISSUE TITLE
Make individual properties permalinkable

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#369]

**Comment by tmcw** [comment]
> visibility is a corner case here, in that it's a property that all layers type have, and is named visibility in each. (We probably should have prefixed it like all the other properties.) - @jfirebaugh 

Low-priority because we don't immediately need to permalink the visibility property, but we do want this to work.

**Comment by jfirebaugh** [comment]
Probably just fix it in v9 with #371.

**Comment by friedbunny** [comment]
#370 broke the [sources](https://www.mapbox.com/mapbox-gl-style-spec/#sources) and [layers](https://www.mapbox.com/mapbox-gl-style-spec/#layers) section header permalinks, as they share `#anchorHashes` with those properties.

**Comment by jfirebaugh** [comment]
Fixed in 04d152b2dc551c0c5a7d822c9dc53135f4722180.
