### ISSUE TITLE
remove "GL" from name

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#373]
Proposal: let's remove "GL" from the name of the specification, calling it the "Mapbox Style Specification".

cc @mapbox/gl @mapbox/support

**Comment by incanus** [comment]
:+1:

**Comment by willwhite** [comment]
Sounds good to me:+1:

**Comment by twbell** [comment]
+1. (More broadly I'd like us to move away from using the GL moniker except
when referencing the rendering tech specifically. Making this argument
elsewhere.)

**Comment by tmcw** [comment]
I'm not 100% in favor of this: Mapbox GL JS isn't going to be renamed and in cases like [mapbox-gl-function](https://github.com/mapbox/mapbox-gl-function), renamed versions like `mapbox-function` won't work.

**Comment by jfirebaugh** [comment]
I don't think we need to or should rename mapbox-gl-function -- it's an implementation library that has no user-facing documentation on www.mapbox.com.

If current patterns hold, we'll eventually rename Mapbox.js ⇢ Mapbox.js Classic and Mapbox GL JS ⇢ Mapbox.js. In the meantime, I'm fine with keeping "GL" in (and only in) "Mapbox GL JS".

**Comment by vicapow** [comment]
how about `vector-tile-style-spec` instead?
