### ISSUE TITLE
Multiple anchors with the same id.

### ISSUE THREAD

**Issue by zerebubuth** [mapbox/mapbox-gl-style-spec#375]
For example: https://www.mapbox.com/mapbox-gl-style-spec/#filter links to the first occurrence of the filter anchor, which links to itself with `<a id="filter" href="#filter">filter</a>`. It seems that what was intended was a link to lower down in the page where there is a second `<a id="filter" class="anchor"></a>` for the "top level" section on filters. Likewise, the navigation menu on the left has a section under "Types" for filter, but that also links to the first occurrence. It seems that the first anchor is either being generated erroneously, or should be namespaced by the "Layers" section that it's in.

**Comment by jfirebaugh** [comment]
Fixed in 04d152b2dc551c0c5a7d822c9dc53135f4722180.
