### ISSUE TITLE
GeoJSON sources use `data` for URLs

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-style-spec#388]
In GeoJSON sources, `data` is used for both specifying inline GeoJSON, and an external URL. We should move latter functionality to `url` and only use `data` for actual GeoJSON.

JS issue: https://github.com/mapbox/mapbox-gl-js/issues/762

**Comment by lucaswoj** [comment]
Closing in favor of #2803 because we're planning to merge this repo into `mapbox-gl-js` in the near future 😄
