### ISSUE TITLE
Add plugins link to documentation

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#390]
The mapbox-gl-js docs are supposed to seamlessly link to the mapbox-gl-style-spec docs. As it stands, only mapbox-gl-js docs have a "Plugins" link in the nav. We should add this link to mapbox-gl-style-spec docs too. 

<img width="822" alt="screen shot 2015-12-16 at 10 27 56 am" src="https://cloud.githubusercontent.com/assets/281306/11850040/e2f87198-a3df-11e5-9edc-cdf6b1064906.png">
<img width="819" alt="screen shot 2015-12-16 at 10 28 06 am" src="https://cloud.githubusercontent.com/assets/281306/11850039/e2f6526e-a3df-11e5-9139-4e1e2bedb0e9.png">

cc @tristen 

ref https://github.com/mapbox/mapbox-gl-js/issues/1821
ref https://github.com/mapbox/mapbox-gl-js/pull/1838

**Comment by tristen** [comment]
Yes, forgot about mapbox-gl-style-spec. Looks like there wasn't 'seamlessness' to begin (with [Overview] in the mix). So I'll add [Plugins] and remove Overview - it links to a product page and is better represented in the new dropdown.

**Comment by lucaswoj** [comment]
:rocket: thanks @tristen!
