### ISSUE TITLE
Document "$id" filters

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#391]
So that they can filter against a [GeoJSON](http://geojson.org/geojson-spec.html#feature-objects) or [Vector Tile](https://github.com/mapbox/vector-tile-spec/tree/master/2.0#42-features) `id` value.

cc @bsudekum

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4104
