### ISSUE TITLE
Render bug with line-pattern

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-style-spec#396]
When choosing a pattern for a line, the pattern seems to be stretched all along the line instead to be tiled.
![image](https://cloud.githubusercontent.com/assets/3670794/11913276/1e0889c2-a65f-11e5-88c9-53eaa0a410ca.png)

PS: I don't know if it is the right repo for this issue.

**Comment by 1ec5** [comment]
The map is being rendered by Mapbox GL JS, so [mapbox/mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js/issues/) is probably the best place to start. (Also, please indicate if you see the same issue in the iOS SDK; we can port any necessary fix to mapbox-gl-native.)
