### ISSUE TITLE
Change the default of "icon-allow-overlap" and "text-allow-overlap" to true

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#405]
I've seen more than one user be confused about why their overlapping symbols are not showing up on the map by default. https://github.com/mapbox/mapbox-gl-js/issues/2005

We should change the default value for `icon-allow-overlap` and `text-allow-overlap` to true.

It'd be an breaking change but mitigated by the migration script.

**Comment by jfirebaugh** [comment]
See ☝️  linked issues for examples of where the current default leads to confusion.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4106
