### ISSUE TITLE
Style validation page?

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-style-spec#406]
Per https://github.com/mapbox/mapbox-gl-js/issues/2011 and [gl-draws own invalid style](https://github.com/mapbox/mapbox-gl-draw/issues/189), it would be nice to have a validation page as part of the style-spec help docs. Going through all of your layout and paint properties and finding which ones are in the wrong spot by hand is prone to mistakes.

**Comment by lucaswoj** [comment]
We addressed this need by bringing the style validator into GL JS
