### ISSUE TITLE
Filter on property existence

### ISSUE THREAD

**Issue by hermansje** [mapbox/mapbox-gl-style-spec#412]
Is there a way in v8 to apply styles based on the existence of a property?

**Comment by hermansje** [comment]
This seems to work (for a property with string values):

```
[
    ">",
    "propertyName",
    ""
]
```

**Comment by jfirebaugh** [comment]
See also #364.

**Comment by hermansje** [comment]
Oh, I hadn't found that issue. A "has" operator would certainly be clearer than this workaround.
