### ISSUE TITLE
Prevent functions from having duplicate stops

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-style-spec#414]
Restore https://github.com/mapbox/mapbox-gl-style-spec/pull/397 with a migration for existing ramps similar to https://github.com/mapbox/mapbox-gl-style-spec/pull/411 for v9.

This behavior was merge in v8 and removed because it was backwards incompatible. The idea is sound and should be part of v9

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4107
