### ISSUE TITLE
Object oriented refactor of validator

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#416]
> I think the validator would benefit greatly from a object-oriented refactoring:
> 
> ```
> var validator = new Validator(style);
> validator.on('error', function(e) { ... });
> validator.validate(); // entire style
> validator.validateSource(source);
> validator.validateLayer(layer);
> validator.validatePaintProperty(key, value, layer);
> validator.validateLayoutProperty(key, value, layer);
> ```

-- @jfirebaugh @ https://github.com/mapbox/mapbox-gl-js/pull/2051

**Comment by tmcw** [comment]
I'm a little confused on this syntax: why would the validator object emit errors instead of returning an array of errors? The validator doesn't do anything async, right?

**Comment by jfirebaugh** [comment]
The principal use case is in mapbox-gl-js, where style/source/tile errors are emitted, not returned.
