### ISSUE TITLE
Text wrap without spaces

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-spec#420]
Languages like Chinese don't employ spaces between characters. How should we handle text wrapping for long labels without spaces?

**Comment by friedbunny** [comment]
We've had some discussions about this elsewhere — https://github.com/mapbox/mapbox-gl-native/issues/1223 and https://github.com/mapbox/mapbox-gl/issues/4 — but no real movement towards implementation yet.

/cc @mikemorris

**Comment by mikemorris** [comment]
Yea, our current line-breaking algorithm is pretty simple, https://github.com/mapbox/mapbox-gl-native/issues/1223 covers the backstory here pretty well. AFAIK this is something that needs to be improved in our renderer, not the style spec.

**Comment by peterqliu** [comment]
cool, closing

**Comment by 1ec5** [comment]
This is happening in mapbox/mapbox-gl-js#3420 and mapbox/mapbox-gl-native#6828.
