### ISSUE TITLE
i want to use my style instead of mapbox://sprites/xxxxxx/xxxx  sprites and glyphs... how to use it.. i don't want sprites and glyphs... in my file ??

### ISSUE THREAD

**Issue by valamanoj001** [mapbox/mapbox-gl-style-spec#422]

**Comment by tmcw** [comment]
Please email help@mapbox.com for support queries.

**Comment by valamanoj001** [comment]
i want my personal style to implement in to my file  instead of spirate ...
how can use it  .. ?

**Comment by valamanoj001** [comment]
i mail on  help@mapbox.com .....

**Comment by valamanoj001** [comment]
i m  not at result from help@mapbox.com
