### ISSUE TITLE
Add "scale-hsla" property for raster layers

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-style-spec#425]
Any plans to include the scale-hsla image filter from Mapnik (and Studio Classic) here?

I don't believe the current controls for rasters https://www.mapbox.com/mapbox-gl-style-spec/#layers-raster provide the full functionality of scale-hsla?

**Comment by lucaswoj** [comment]
Merged into https://github.com/mapbox/mapbox-gl-js/issues/3889
