### ISSUE TITLE
Text properties for circle types

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-style-spec#426]
It would be great if the [circle type](https://www.mapbox.com/mapbox-gl-style-spec/#layers-circle) also supported text properties like it's close cousin "symbol". I've often wanted to put centered text in a circle and in order to achieve this currently I need to create an svg circle, hard code it into a style and then paint a symbol property with it.

**Comment by peterqliu** [comment]
@tristen have you tried a symbol layer for the text, atop a circle layer for the circle?

**Comment by tristen** [comment]
Ah right, that's another technique. But still! creating two layers for this use-case is a little verbose and it's confusing if the layer also has interactive qualities to it.

**Comment by jfirebaugh** [comment]
This would almost certainly snowball into requiring support for all the properties and behaviors of symbol layers: collision / placement logic, font selection, offsets and justification, etc. We wouldn't want to implement all that twice, so we should basically consider this feature request as: "merge the `symbol` and `circle` layer types".

**Comment by peterqliu** [comment]
per chat, what if we folded circle into a symbol property? Each symbol can have text, image, and/or circle. Would keep things nice and `DRY`

**Comment by jfirebaugh** [comment]
I think we should keep the existing layer types.
