### ISSUE TITLE
v8.json require json-loader when using webpack

### ISSUE THREAD

**Issue by alex3165** [mapbox/mapbox-gl-style-spec#435]
Would be nice to not constrain webpack user to have json-loader when using mapbox-gl, the error that we have if we don't use json-loader:

```
ERROR in ./~/mapbox-gl-style-spec/reference/latest.js
Module not found: Error: Cannot resolve module 'json' in [path]/node_modules/mapbox-gl-style-spec/reference
 @ ./~/mapbox-gl-style-spec/reference/latest.js 1:17-37
```

The solution would be to bundle the latest.js file with v8.json together into a js file.

**Comment by jfirebaugh** [comment]
Use of mapbox-gl-js with webpack is now documented [here](https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-webpack).
