### ISSUE TITLE
Support for fill-blur?

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-style-spec#436]
Any reason to not support blurs on areas?

Use case: As a cartographer I want to soften the borders of coarse landuse features like urban areas and forests at low zoom levels.

<img width="249" alt="screenshot 2016-03-28 21 35 58" src="https://cloud.githubusercontent.com/assets/126868/14082336/227bdff0-f52d-11e5-803d-2fe45a637816.png">

**Comment by tmcw** [comment]
We used to support blur. Back discussion is at https://github.com/mapbox/mapbox-gl-style-spec/issues/232

**Comment by planemad** [comment]
@tmcw ok, as a workaround I created a duplicate line layer and used line-blur to get the desired effect. Would have been cool if this was just a one step process.

<img width="175" alt="screenshot 2016-03-28 22 30 43" src="https://cloud.githubusercontent.com/assets/126868/14083713/bd3b6234-f534-11e5-8424-22b81f16ae19.png">
