### ISSUE TITLE
mapbox-gl-style-spec #glyph

### ISSUE THREAD

**Issue by Ccantey** [mapbox/mapbox-gl-style-spec#440]
Update style reference:

`"glyphs": "mapbox://fonts/mapbox/{fontstack}/{range}.pbf"`

to

`"glyphs":"mapbox://fonts/:username/{fontstack}/{range}.pbf"`

per https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md

seems to break labeling without this change

**Comment by tmcw** [comment]
Wouldn't it be `{username}` to follow the existing pattern?

**Comment by Ccantey** [comment]
sorry, copied and pasted from changelog

> The format for mapbox:// style and glyphs URLs has changed. For style URLs, you should now use the format mapbox://styles/:username/:style. The :style portion of the URL no longer contains a username. For font URLs, you should now use the format mapbox://fonts/:username/{fontstack}/{range}.pbf.

**Comment by jfirebaugh** [comment]
There are two different levels of substitutions here. `{fontstack}` and `{range}` should appear literally in the `glyphs` value of a style -- they are placeholders that the renderer implementation will fill in at runtime.

`:username` is a value that the style author is expected to replace with their own Mapbox account name (or by "mapbox" if the style is using predefined default fonts).

**Comment by Ccantey** [comment]
Makes sense, I'm trying to work with MapZen source
