### ISSUE TITLE
Style json keys should not contain dots (.) or start with a dollar sign ($)

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-style-spec#446]
I am trying to store style json in mongodb. Mongodb complains that keys must not contain '.' or start with a dollar sign ($). I found that metadata keys contain dot sign. 
Also, paint property can have dot sign to specify class-specific paint properties. I think can be use nested keys instead, such as:

``` js
paint.light : {
}

paint: {
  light: {
  }
}
```

**Comment by jfirebaugh** [comment]
I don't think it makes sense to limit the style specification to a subset of JSON just to support the limitations of some particular third-party database implementation. If mongodb doesn't support JSON, you'll need to stringify before storage.
