### ISSUE TITLE
3d extrusion (buildings etc) spec

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-style-spec#456]
Spinning off of https://github.com/mapbox/mapbox-gl-js/issues/684#issuecomment-221713082: I've reimplemented @ansis's 3d building demo ([js branch](https://github.com/mapbox/mapbox-gl-js/tree/building-redux); [spec branch](https://github.com/mapbox/mapbox-gl-style-spec/tree/buildings); [shader branch](https://github.com/mapbox/mapbox-gl-shaders/tree/js-buildings)). That code is ported pretty faithfully from the demo, except that I've renamed `building` to `extrusion` everywhere: it 
- adds a new `extrusion` type (in which one would specify a polygon source layer)
- hardcodes a light direction
- extrudes a height based on a feature's `properties.levels` (the demo is done based on a source from @ajashton with this property), or falls back to a hardcoded `levels` integer
- I also added a `extrusion-shadow-color`, which colors the shadow tint (but is pretty subtle; doesn't change the amount of possible shadowing)

I propose the following additions to the spec (:warning: not all of which are yet implemented):
- We add a new `extrusion` type. At present it _only_ extrudes polygons. We may add support for extruding lines and points in the future, given compelling use cases/need.
- Extrusion properties:
  - layout:
    - `visibility`
    - Presumably there will be additional layout properties concerning label placement etc once more cases are tested
  - paint:
    - `extrusion-color`
    - `extrusion-shadow-color` (open to other naming suggestions -- @tmcw might have one)
    - `extrusion-opacity` (I'm on the fence about this as it can create [weird ghostly buildings](https://twitter.com/lbudorick/status/735603614916444162), but can support if people find ghostly buildings compelling)
    - `extrusion-pattern`: implementation has been punted so far but I fear this should probably exist
    - `extrusion-antialias`
    - `extrusion-outline-color` (and if so, what should an extrusion outline be? Just the base? Other edges? (Hint: I haven't done other edges))
    - `extrusion-translate`
    - `extrusion-translate-anchor`
    - `extrusion-height`: Though undoubtably there are cases to extrude not based on data (@1ec5 would here point out that the buildings in DC are more or less all the same height _by law_), **I think it's important this new type be DDS-first**.
    - `extrusion-lighting-anchor` (whether a lighting direction should be oriented to map or viewport)
- APIs:
  - `map.setLightDirection` to change lighting

@mapbox/gl @mapbox/cartography-cats

**Comment by 1ec5** [comment]
> `extrusion-opacity` (I'm on the fence about this as it can create [weird ghostly buildings](https://twitter.com/lbudorick/status/735603614916444162), but can support if people find ghostly buildings compelling)

Some values of `extrusion-opacity` might lead to weird effects like the one you found, but Google Maps makes its buildings subtly transcluent to prevent tall buildings from completely obscuring surrounding streets.

> `extrusion-pattern`: implementation has been punted so far but I fear this should probably exist

Would the use case would be for, say, a realistic texture for stone façades or a window pattern on office buildings?

> `map.setLightDirection` to change lighting

I think this would be useful for terrain lighting, too.

In addition to the lighting source’s azimuth, what about its altitude? The sun (or moon) would need to be much lower to accommodate a sunrise or sunset effect.

> extrudes a height based on a feature's `properties.levels` (the demo is done based on a source from @ajashton with this property), or falls back to a hardcoded `levels` integer

Aside: Cantilevered building structures or pedestrian bridges that have a significant horizontal footprint would need a `min-levels` or `min-height` property. I think it would be useful to consider these cases even in a simple extrusion model that doesn’t account for unusual building shapes.

**Comment by ajashton** [comment]
Awesome. We'll also need something like `extrusion-height-factor` (or https://github.com/mapbox/mapbox-gl-style-spec/issues/47) since height data will be in a variety of units (levels, meters, feet, some other non-height data to visualize such as population density).

**Comment by ajashton** [comment]
> Cantilevered building structures or pedestrian bridges

There are loads of other of odd building shapes that are not suitable for simple extrusion. Since many of these are important landmarks that can't be ignored, we'll probably need some kind of separate true 3d modelling - maybe cantilevers and sky bridges would best be preprocessed into whatever this format ends up being rather than having special extrusion handling for them?

**Comment by peterqliu** [comment]
> would need a min-levels or min-height property

Would such a 3D shape levitate in midair? or would it rest on a second, smaller shape?

**Comment by lbud** [comment]
@peterqliu these
![image](https://cloud.githubusercontent.com/assets/3170312/15582167/8dad309c-233d-11e6-9368-d6eeea74cb5f.png)
are actually tons of little polygons extruded separately to form complex buildings ([see e.g.](http://www.openstreetmap.org/relation/2098969)). I would assume in the case of pedestrian bridges or cantilevered buildings they would be relations similarly modeled with multiple polygons, some powerless to gravity. But I agree with @ajashton: let's handle simple extrusion cases first…

**Comment by 1ec5** [comment]
> Would such a 3D shape levitate in midair? or would it rest on a second, smaller shape?

In the source being used in @lbud’s demo, each building _part_ is extruded individually, so imagine Fallingwater being represented by a number of building parts, some of which have a `min-height`. (In OpenStreetMap, the `min_height` and `building:min_level` tags are used even in areas that aren’t more meticulously mapped according to the “[simple 3D buildings](http://wiki.openstreetmap.org/wiki/Simple_3D_buildings)” scheme.)

> maybe cantilevers and sky bridges would best be preprocessed into whatever this format ends up being rather than having special extrusion handling for them?

I don’t think it’s strictly necessary to support arbitrary building shapes in order to support raised features as part of extrusion. Or perhaps the concept should be generalized so that, for instance, a point feature can levitate above a tilted map. Such a property would be useful for the “user location dot” or “course puck” that is typically drawn with a drop shadow, as if levitating, in mobile map SDKs. But for buildings, I think the concept of a “knocked-out” floor is not merely decorative and also not necessarily tied to true 3D modeling.

**Comment by andreasviglakis** [comment]
this is great.

> but Google Maps makes its buildings subtly transcluent to prevent tall buildings from completely obscuring surrounding streets.

👍 

> Would such a 3D shape levitate in midair?

yes? but no, not really.

![image](https://cloud.githubusercontent.com/assets/7102075/15582448/f2b68fd2-2325-11e6-9d2f-3e8d033aa5a8.png)

how would this spec deal (now or in the future) with complex but critical edge cases like the eiffel tower? would this be covered by "support for extruding lines and points?"

**Comment by lucaswoj** [comment]
> At present it only extrudes polygons. We may add support for extruding lines and points in the future, given compelling use cases/need.

Would it be possible to add the `extrude-*` properties to the existing `fill` (and eventually `line`and `point`) types rather than adding a new layer type?

**Comment by lbud** [comment]
Hmm. @lucaswoj — I considered this, but ultimately I think it makes more sense to create a new layer type (also, I should note I'm _very_ skeptical about use cases for extruding lines and points*):
- The intention behind filling in a flat area of land (or water) vs that behind creating three-dimensional shapes feel inherently very different
- Lighting affects the flat surface of an extrusion in addition to its walls, meaning without writing separate cases for this, a light source would change the color of even an unextruded fill
- Everything else about the bucket/shader code would have to be very `if/else` anyway, and it would be much cleaner to keep these separate

\* I'd also add that I _do_ see the case for raising, say, a point (circle/symbol type) on a map, but I wouldn't consider those "extrusions" — "extrusion" here isn't so much "raise this thing on the map" as it is "turn this into a vertical prism/give it walls."

**Comment by 1ec5** [comment]
There are use cases for extruding lines and points, as opposed to having them levitate. For example, you might want to place an [elevation profile on the map](https://www.mapbox.com/blog/dc-bikeshare-revisited/), or mark cities with extruded points whose heights correspond to population or some other attribute.

**Comment by lbud** [comment]
Alright; maybe we'll do those later.

**Comment by peterqliu** [comment]
If it's not a significant scope creep, negative extrusions would be useful for things like strip mines/sinkholes.

edit: can just be a rectilinear cavity, not a complex shape or mesh

**Comment by lbud** [comment]
@peterqliu unfortunately that is a significant scope creep for now.

edit: re edit: still significant scope creep

**Comment by lucaswoj** [comment]
> - APIs:
>   - `map.setLightDirection` to change lighting

Could this be a [root property](https://www.mapbox.com/mapbox-gl-style-spec/#root) on the style? We would still need a `Map#setLightDirection` method.

---

Otherwise, :shipit: on this spec 😄

**Comment by lucaswoj** [comment]
> Lighting affects the flat surface of an extrusion in addition to its walls, meaning without writing separate cases for this, a light source would change the color of even an unextruded fill

Will the map look funny in any situations if the lighting doesn't affect unextruded fills?

**Comment by scothis** [comment]
👍 for adding `lightDirection` to the root of the style. It will fit nicely alongside the defaults for `center`, `zoom`, `bearing` and `pitch`. Only concern is that we should feel comfortable that this is the only lighting setting we want to have because it will be annoying to update/deprecate it later.

**Comment by nickidlugash** [comment]
@scothis we're actually thinking now of adding a `light` object to the root of the style, which will have direction, anchor, and color properties. We'll update this ticket later today with a revision of the full proposal /cc @lbud

**Comment by nickidlugash** [comment]
Here's an update to @lbud's and my proposed style spec changes:
- Root properties:
  - **`light`** | Optional object
    - **`light-anchor`** | Optional enum. Default: `viewport`
    - **`light-direction`** | Optional array. Default: `[-0.5, -0.3, 1.0]`
    - **`light-color`** | Optional color. Default: `rgba(1, 1, 1, 0.75)` *
- Extrusion properties:
  - Layout:
    - **`visibility`** | Optional enum. Default: `visible`
  - Paint:
    - **`extrusion-height`** | Optional number. Default: `1` (meter)
    - **`extrusion-min-height`** | Optional number. Default: `0` (meter) *
    - **`extrusion-color`** | Optional color. Default: `#929292`
    - **`extrusion-layer-opacity`** | Optional number. Default: `1` *
    - **`extrusion-pattern`** | Optional string
    - **`extrusion-antialias`** | Optional boolean. Default `false`
    - **`extrusion-outline-color`** | Optional color. Matches `extrusion-color` if unspecified
    - **`extrusion-translate`** | Optional array. Default `[0, 0]`
    - **`extrusion-translate-anchor`** | Optional enum. Default: `map`
- APIs:
  - **`map.setLightProperty`**
    - e.g. `map.setLightProperty({light-anchor: "map", light-color: "#f00"})` 

_Notes_
-  the alpha value in `light-color` is the light intensity.
-  `extrusion-min-height` is the height to _start_ extruding from. This corresponds to the concept of `min-height` in OSM.
-  `extrusion-layer-opacity`is per-layer opacity, unlike the `-opacity` properties of other layer types which are per-feature, because per-feature opacity for extrusions results in unexpected behavior. We may be able to add an `extrusion-opacity` property for per-feature opacity in the future.
-  Shading color is currently affected by a combination of the `extrusion-color` and `light-color` properties. There is no specific `shading-color` property, although we could potential add that in the future if needed.

**Comment by 1ec5** [comment]
What unit is `light-direction` expressed in? Is it a real-world unit?

**Comment by dpieri** [comment]
Is this spec being designed with future support for 3D terrain meshes in mind?

**Comment by gatelli** [comment]
Amazing ! Do you have an idea of the release date ?

**Comment by lucaswoj** [comment]
> - Root properties:
>   - **`light`** | Optional object
>     - **`light-anchor`** | Optional enum. Default: `viewport`
>     - **`light-direction`** | Optional array. Default: `[-0.5, -0.3, 1.0]`
>     - **`light-color`** | Optional color. Default: `rgba(1, 1, 1, 0.75)` *

Why a `light` object rather than putting the `light-*` properties directly in the root of the stylesheet? These properties are double-namespaced.

---

> - APIs:
>   - **`map.setLightProperty`**
>     - e.g. `map.setLightProperty({light-anchor: "map", light-color: "#f00"})` 

The other `Map#set*Property` methods have a signature like `map.setLightProperty('light-anchor', 'map')`. I like this new signature too! If we're going to support it, we should support it everywhere. 

---

> -  `extrusion-min-height` is the height to _start_ extruding from. This corresponds to the concept of `min-height` in OSM.

I appreciate that this is the naming convention established by OSM.
I also think it could be confusing to users who expect it to behave like CSS's `min-*` properties in the context of a stylesheet.
Perhaps a name like `extrusion-bottom-height` would be less surprising.

**Comment by jfirebaugh** [comment]
What is the function of `extrusion-outline-color`? Does this stroke the edges of the extrusion? Is there potential for regretting this property, [as we do with `fill-outline-color`](https://github.com/mapbox/mapbox-gl-style-spec/issues/240)?

> per-feature opacity for extrusions results in unexpected behavior

Can you say more about this? E.g. is it a technical limitation or a bug in the current code that we haven't tracked down yet? What happens if you use something like `"extrusion-color": rgba(255, 0, 0, 0.5)` in lieu of `"extrusion-color": rgb(255, 0, 0), "extrusion-opacity": 0.5`?

> Perhaps a name like `extrusion-bottom-height` would be less surprising.

Or even simply `extrusion-bottom` + `extrusion-top`, a la CSS?

**Comment by nickidlugash** [comment]
> > Perhaps a name like extrusion-bottom-height would be less surprising.
> 
> Or even simply extrusion-bottom + extrusion-top, a la CSS?

These are probably better options than `extrusion-min-height`. I think specifying that these are `-height` properties is important (I could be wrong, but I think the only CSS properties that are not specific in this way are the shorthand properties that combine multiple properties). So maybe either:
1. `extrusion-height` + `extrusion-bottom-height`
2. `extrusion-top-height` + `extrusion-bottom-height` ?

It's a bit long-winded, but maybe the second option is better, for clarity and just to be more parallel?

**Comment by 1ec5** [comment]
The only information that “height” provides in this context is that “top” and “bottom” are measured along the vertical (altitudinal) axis. But “top” and “bottom” already provide this context. In CSS, when an element is absolutely positioned, `top` and `bottom` also represent absolute values along the vertical axis; no `-height` or `-depth` suffix is needed.

**Comment by peterqliu** [comment]
Are there situations (even in the future) when an `extrusion-bottom` or `extrusion-min-height` can actually be above the "top" of the extrusion? This might happen if we support negative extrusions in the future, and would be confusing.

> extrusion-min-height is the height to _start_ extruding from. This corresponds to the concept of min-height in OSM.

how about some form of `extrusion-start`?

**Comment by lbud** [comment]
> What unit is `light-direction` expressed in? Is it a real-world unit?

@1ec5 No, it's a three-dimensional `x, y, z` vector, where `[0,0,0]` would represent light coming from inside an individual extrusion. The higher the number, the more intense the light, both in the positive and negative direction. I'm not entirely sure what's the best way to communicate this yet…

**Comment by lbud** [comment]
> Is this spec being designed with future support for 3D terrain meshes in mind?

@dpieri Presumably global map lighting properties _could_ be used if we were ever to support 3D terrain meshes, but that's not really on our radar at the moment.

**Comment by lbud** [comment]
> Do you have an idea of the release date ?

@gatelli We're hoping to release a version of gl-js supporting extrusions in early September, with gl-native support coming later.

**Comment by lbud** [comment]
> Why a `light` object rather than putting the `light-*` properties directly in the root of the stylesheet? These properties are double-namespaced.

@lucaswoj I think the idea was for organizational purposes, though I would be open to letting all three be their own root properties. What would you prefer @lucaswoj @jfirebaugh?

**Comment by lbud** [comment]
> What is the function of `extrusion-outline-color`? Does this stroke the edges of the extrusion? Is there potential for regretting this property, as we do with `fill-outline-color`?

@jfirebaugh Right, this strokes the edges of the extrusion:
![image](https://cloud.githubusercontent.com/assets/3170312/17874401/478af6fc-6880-11e6-81f0-9cdd843dd9c1.png)
There is definitely potential for regretting this property. I say this mostly because one of my biggest looming concerns is antialiasing — I punted on [FXAA](https://en.wikipedia.org/wiki/Fast_approximate_anti-aliasing) as it looked a little too blurry for usage in maps. The above screenshot is on a retina screen but on non-retina it's much more ants-crawling, and outlines certainly exacerbate that:
![image](https://cloud.githubusercontent.com/assets/3170312/17874382/2af97d06-6880-11e6-8726-37e3703ac5de.png)

> > per-feature opacity for extrusions results in unexpected behavior
> 
> Can you say more about this? E.g. is it a technical limitation or a bug in the current code that we haven't tracked down yet? What happens if you use something like `"extrusion-color": rgba(255, 0, 0, 0.5)` in lieu of `"extrusion-color": rgb(255, 0, 0), "extrusion-opacity": 0.5`?

The two main problems with per-feature opacity are showing lots of interior walls and overlapping opacity at tile boundaries. The interior walls issue is one of imperfect data/data format: what we have is a big collection of polygonal building parts with height data assigned (from OSM). We don't do any kind of three-dimensional merge operations, so we render the complete bottom-to-top extrusion for every building part. Per-feature opacity of 0.7 would therefore look like this:
![image](https://cloud.githubusercontent.com/assets/3170312/17874565/57ba1746-6881-11e6-86b1-8a4b129f3009.png)

whereas per-layer opacity (rendered to a separate texture and then rendered at specified opacity to the map) looks like
![image](https://cloud.githubusercontent.com/assets/3170312/17874630/c64a3966-6881-11e6-9eb5-2a4558ffb394.png)

We also draw slight overlaps at tile boundaries with a per-opacity approach: I think we could clip these buffers if we needed to, but I see the former issue as prohibitive.

**Comment by lbud** [comment]
> What happens if you use something like "extrusion-color": rgba(255, 0, 0, 0.5) in lieu of "extrusion-color": rgb(255, 0, 0), "extrusion-opacity": 0.5?

@jfirebaugh I'd like to specify that non-1 alpha values specified in this property won't be respected — does that seem okay? (Alternatively we could make an `rgba` extrusion-color a shorthand way of specifying an `rgb` extrusion-color with `a` extrusion-layer-opacity, but that feels very wrong.)

**Comment by jfirebaugh** [comment]
I suggest renaming `extrusion-outline-color` ⇢ `extrusion-edge-color` to make it a bit more self-explanatory. No strong opinion about keeping the feature or not.

Thanks for the explanation about opacity, makes sense.

> I'd like to specify that non-1 alpha values specified in this property won't be respected — does that seem okay?

Sounds reasonable.

**Comment by 1ec5** [comment]
> > What unit is `light-direction` expressed in? Is it a real-world unit?
> 
> @1ec5 No, it's a three-dimensional `x, y, z` vector, where `[0,0,0]` would represent light coming from inside an individual extrusion. The higher the number, the more intense the light, both in the positive and negative direction. I'm not entirely sure what's the best way to communicate this yet…

A starting point would be to think about use cases:
- If I want to make a backlit map of Manhattan, what value should I use for `light-direction`?
- If I want to simulate [Manhattanhenge](https://en.wikipedia.org/wiki/Manhattanhenge) and have the light source come in from the northwest, regardless of the map’s bearing, what value should I use for `light-direction`? (Is it even possible to configure a fixed light source this way?)

Even understanding why a normalized vector is used to control the light source, it strikes me as counterintuitive that an ostensibly directional property also controls intensity. So if I’m happy with the default lighting direction but just want the light to be a bit less intense, I need to adjust the lighting direction.

**Comment by scothis** [comment]
Also agree that `extrusion-min-height` is a strange name. I interpret it as setting a value a the height cannot be less than `Math.max(minHeight, height)`. Something like `extrusion-base-height` is more clear to me, as the value is where the extrusion starts from.

**Comment by nickidlugash** [comment]
`extrusion-height` + `extrusion-base-height` sounds good to me.

**Comment by lucaswoj** [comment]
I would like to revisit this proposal

> Would it be possible to add the `extrude-*` properties to the existing `fill` (and eventually `line`and `point`) types rather than adding a new layer type?

There has been continued interest in extruding lines, points, and circles. The implementation of this functionality may be done later but the specification design must be considered now. The cleanest way to implement this functionality is to allow `extrude-*` properties on other layer types. 

---

> The intention behind filling in a flat area of land (or water) vs that behind creating three-dimensional shapes feel inherently very different

The only reason `fill` layers are flat is because we haven't implemented extrusions yet. 

> Lighting affects the flat surface of an extrusion in addition to its walls, meaning without writing separate cases for this, a light source would change the color of even an unextruded fill

I find it surprising that the top of an extrusion is colored differently than a fill layer. This implies that lighting is applied inconsistently to different layer types. That'd be surprising whether `fill` and `extrusion` are separate layer types or not. 

> Everything else about the bucket/shader code would have to be very `if/else` anyway, and it would be much cleaner to keep these separate

We can keep the implementations separate and hide that implementation detail from the spec.

> \* I'd also add that I _do_ see the case for raising, say, a point (circle/symbol type) on a map, but I wouldn't consider those "extrusions" — "extrusion" here isn't so much "raise this thing on the map" as it is "turn this into a vertical prism/give it walls."

A quick search indicates that 3d modeling software ([Blender](https://www.blender.org/manual/modeling/meshes/editing/duplicating/extrude.html#extrude-edges-and-vertices-only), Sketchup) supports "extruding" lines and points.

**Comment by 1ec5** [comment]
> > \* I'd also add that I _do_ see the case for raising, say, a point (circle/symbol type) on a map, but I wouldn't consider those "extrusions" — "extrusion" here isn't so much "raise this thing on the map" as it is "turn this into a vertical prism/give it walls."
> 
> A quick search indicates that 3d modeling software ([Blender](https://www.blender.org/manual/modeling/meshes/editing/duplicating/extrude.html#extrude-edges-and-vertices-only), Sketchup) supports "extruding" lines and points.  

Indeed, but as I pointed out in https://github.com/mapbox/mapbox-gl-style-spec/issues/456#issuecomment-221975589, I think there’s a distinction to be made between “levitating” a layer (raising it above the ground) and extruding it (giving it a support structure). Is it extrusion if you take a 2D layer and levitate it without giving it any depth?

Consider a map that has extruded buildings, so you want the Maki POI markers to levitate with leader lines extending from the POIs down to the ground, to avoid any ambiguity around depth. The symbol layer for the POI markers would be levitated, while the leader lines would be implemented as extruded point layers. Google Maps does something like this on the Web (in 3D Earth view), although it would be awesome to be able to vary the vertical offset by the POI’s importance. Maybe it’s already possible using `icon-offset`, though.

Implementation-wise, should we treat levitation as a special case of extrusion regardless (`extrusion-base-height` equaling `extrusion-height`)?

**Comment by lbud** [comment]
Alright team, you've got me convinced.

@mapbox/gl @peterqliu 

Increasing use cases for 3d maps (navigation, gaming) definitely present use cases for
- extruding geometries
  - extruding fills (buildings ++)
    ![image](https://cloud.githubusercontent.com/assets/3170312/18180629/9e775e6a-703c-11e6-96cd-956a05525b66.png)
  - extruding lines 
    ![image](https://cloud.githubusercontent.com/assets/3170312/18180622/8f5febf4-703c-11e6-99b8-c3ec7b515cd2.png)
  - extruding circles (data viz) 
- levitating geometries
  - levitating lines
    ![image](https://cloud.githubusercontent.com/assets/3170312/18184028/efc0f68c-704b-11e6-98b4-5f7b900ab446.png)
  - levitating points (symbols)
  - and, likely, levitating fills

Levitation use cases will be addressed in https://github.com/mapbox/mapbox-gl/issues/6. But we will design the spec in a way that makes it more extensible for extruding multiple geometry types. 

As such we are modifying this spec proposal: presently,
- the `extrusion` type is no more
- `fill` types will have an additional
  - `fill-extrude-height` (default: 0)
  - `fill-extrude-base` (default: 0)

In the future we'll add the same properties to `line` types, and eventually also likely `circle` types.

At present this means we'll handle `fill-opacity` without extrudes and `fill-opacity` with extrudes differently, the former on a per-feature basis (as it currently is) and the latter on a per-layer basis. All other fill properties can still apply directly to extruded fills (extrusion-color -> fill-color, extrusion-pattern -> fill-pattern, -translate, -translate-anchor, etc).

The biggest catch in this is that as soon as a feature is extruded it will also be affected by the map's lighting. The current in-progress implementation of extrusions treats `extrusion-color` as the surface color of an object and lights all sides (including the top) accordingly, so lighting will make the tops of extruded fills look different from flat fills.

**Comment by lbud** [comment]
(I'm flexible on exact wording of `[type]-extrude-height` and `[type]-extrude-base`)

**Comment by nickidlugash** [comment]
Just noting here that our roadmap doesn't currently include the ability to create 3D leader lines (I suppose you could hack something together with a symbol layer + circle layer, but they wouldn't be related to each other, so collisions would be inconsistent). I think this is fine for now, as you also can't currently create 2D leader lines either. Leader lines in general may need special implementation in the symbol layer.

**Comment by lbud** [comment]
Closing as implemented — will open tickets for other 3d properties as needed.

**Comment by bensleveritt** [comment]
@lbud Is there a plan to create tickets for levitated line and circles? After playing with the extrusion layer (and loving it), it'd be great to get lines that correlated vertically with their extrusion. Also circles.

**Comment by lbud** [comment]
@bensleveritt there's discussion happening at https://github.com/mapbox/mapbox-gl/issues/6 about how we may approach "levitated" features.

**Comment by bensleveritt** [comment]
@lbud Thanks, I did see that, but I wasn't sure it was the most up to date tracking of the feature.

**Comment by phprad** [comment]
How do you style individual building.
How can one loop through the building to gets the bounding coordinates of a building.
Thanks

**Comment by lbud** [comment]
Hi @phprad, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by strech345** [comment]
Does i understand right, properties like `extrusion-antialias` was removed? Is there a way to enable it anyway?

**Comment by lbud** [comment]
That's right @strech345, there is no antialias or outline property for fill-extrusions.

**Comment by strech345** [comment]
Hello @lbud ,
thanks, coud you explain why this was removes and if this will come again?

**Comment by lbud** [comment]
Sure, `fill-extrusion-antialias` was a bit of a misnomer as it essentially implemented 1px outlines (like `fill-antialias` does) without actually using the same antialiasing technique `fill-antialias` does, so it did not effectively provide antialiasing, and we deemed outlines unnecessary. We experimented with another antialiasing technique that didn't provide great results either and therefore removed this property.

**Comment by strech345** [comment]
Hello @lbud ,
thanks.
Do you know if someone is working on it and if it will include in future?

**Comment by lbud** [comment]
It is not under active development or prioritized at this time.
