### ISSUE TITLE
Include clustering options in documentation

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-style-spec#463]
The clustering options `cluster`, `clusterRadius`, and `clusterMaxZoom` are [present in the spec definition](https://github.com/mapbox/mapbox-gl-style-spec/blob/194fc55b6a7dd54c1e2cf2dd9048fbb5e836716d/reference/v8.json#L173-L186), but do not appear in the docs because `source` properties aren't included dynamically the way that root, `layer`, `layer.layout`, and `layer.paint` properties are.

Option 1: simply document the cluster\* options manually in the narrative docs.
Option 2: start including dynamically the source properties.

Option 1 is quicker, but more brittle and less complete, so fwiw I'd vote for option 2.

**Comment by lucaswoj** [comment]
Both 1 and 2 sound good to me. My sense is that 2 will not take much more effort than 1.
