### ISSUE TITLE
Allow arbitrary expressions in functions, filters, and cluster aggregators

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#47]
Will it be possible to support `+`, `-`, `*`, and `/`?

**Comment by jfirebaugh** [comment]
Can we enumerate some uses cases for this feature? I'm particularly interested in how much it overlaps with #226 (Stop functions based on arbitrary properties).

**Comment by nickidlugash** [comment]
hrm. In theory, there are some use cases for this not covered by stop functions based on arbitrary properties. I might not be fully understanding the stop functions, but they seem to mainly be for assigning different values of the same style property for different values of the same field in a data layer. With math operators, you could manipulate values across different properties and different GL layers. 

A use case that I think would overlap with a use case for https://github.com/mapbox/mapbox-gl-style-spec/issues/226 is using math operators in conjunction with tokens, e.g. for building heights. 

The two main non-overlapping use cases I had in mind for this were for creating systems of line widths and font sizes across different GL layers. These could potentially be really useful for creating template styles that are fast to customize. However, these use cases require the ability to use constant values in functions, which you currently can't do in the editor.

**Comment by danpat** [comment]
I have a specific use case.  I'm generating vector tiles from OSRM that contain speed values on roads, in km/h.  It would be nice to show localized values (`mph` vs `km/h`) by doing some simple math in the style.

I'm ambivalent about the syntax, but I've found this capability in Mapnik hugely useful.

Other basic math functions, like `round()` would also be helpful in my case.

**Comment by timrobertson100** [comment]
A use case:

Given vector tiles containing polygons which represent sales regions.  Each polygon is accompanied with data giving sales totals for a range of months in an attribute list (e.g. Month1:€10000, Month2:€23000 etc).  You want to do a visualisation with a double handled time slider, where the user selects the period (e.g. month23-month45) and the polygons are then coloured based on total sales in the month ranges - this lets the user explore which regions are hot over different time ranges.  You need to do math across feature attributes to total them up, and they can't be predetermined, as the slider control on the page is not known in advance.  

As far as I can tell from my (very limited) use, this is not possible using filters.

_(If this is possible, can you please point me at how - I am trying to find ways around this at the moment)_

**Comment by stackTom** [comment]
@timrobertson100 have you found a solution to this problem?

**Comment by timrobertson100** [comment]
@stackTom - I ended up doing server side processing on UI changes as I couldn't find a way in filters.

**Comment by jfirebaugh** [comment]
See https://github.com/mapbox/mapbox-gl/issues/15 for additional syntax proposals.

**Comment by lucaswoj** [comment]
Let's continue the conversation from https://github.com/mapbox/mapbox-gl-function/issues/28 here 😄 

To summarize so far:

 - Arbitrary expression functions will make our filters, functions, and cluster aggregators more powerful & flexible 
 - Implementing arbitrary expressions will be challenging because they may need to run on the GPU 
 - We are leaning towards a lispy syntax comprised of nested arrays 
 - Devising a workable GUI for arbitrary expressions may be a challenge.

**Comment by lucaswoj** [comment]
@1ec5 Agreed, creating a point & click GUI for this will be a little tricky. I'm not sure that users demand a point and click GUI for this, however. Most computer users are familiar with the notion of editing formulas, in Excel or Numbers for example.

**Comment by 1ec5** [comment]
> Most computer users are familiar with the notion of editing formulas, in Excel or Numbers for example.

I have no qualms about an inline, text-based GUI for arithmetic or statistical expressions. But as soon as you introduce the notion of [conditionals](https://support.office.com/en-us/article/IF-function-69aed7c9-4e8a-4755-a9bc-aa8bbff73be2), you get a mini string language – an outcome that we took #104 on a tangent to avoid.

**Comment by lucaswoj** [comment]
Important use cases: 

 - unit conversion
 - number formatting
 - token defaults
 - customizable interpolation
 - arithmetic on feature properties within functions

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4077
