### ISSUE TITLE
Extend style spec for data-driven raster layer

### ISSUE THREAD

**Issue by Scarysize** [mapbox/mapbox-gl-style-spec#476]
So, we are currently implementing a raster layer with data-driven styling: Our tile server delivers greyscale tile images, where the grey value represents an actual data value. We map that data value to a color value using our own fragment shader.

EDIT: To clarify, greyscale tiles save us a lot of traffic to the front-end (we measured this extensively). That's why we are doing the color mapping on the client side.

The rendering stuff works as intended, but we have issues extending the style specification to allow the follow:

``` js
map.addLayer(
  type: 'data-driven-raster',
 // ... define tile source etc.
  paint: {
    'raster-color-mapping': [
      [0, 'rgba(255, 255, 255, 0.5)']
      [10, 'rgba(128, 13, 255, 0.5)']
      [54, 'rgba(0, 0, 0, 0.5)']
      // ... etc, more color stops
    ]
  }
)
```

This is what we tried in the style specification json:

``` json
"raster-color-mapping": {
      "type": "array",
      "value": {
        "type": "array",
        "length": 2,
        "value": "number"
      },
      "doc": "The color mapping of the data tiles.",
      "function": "interpolated",
      "zoom-function": true,
      "property-function": true,
      "transition": true,
      "sdk-support": {
        "basic": {
          "js": "0.10.0",
          "ios": "2.0.0",
          "android": "2.0.1"
        },
        "property-function": {
          "js": "0.18.0"
        }
      }
    }
```

Could you point us in the right direction?

**Comment by andrewharvey** [comment]
I understand this issue as _Add "raster-colorizer" property for raster layers_  similar the same feature in TileMill https://www.mapbox.com/blog/tilemill-raster-colorizer/.

I see a lot of value in supporting this. It would make it easy to produce the flood maps from https://www.mapbox.com/blog/terrain-rgb/ in GL JS, as simple as setting the raster-colorizer paint property (a user driven height variable could directly set the paint property).

I think it makes sense to tie it in with the terrain-rgb style of encoding a single band source raster into 3 band rgb pngs. So users who upload single band geotiffs of type Int16 as a Tileset get terrain-rgb's which they can style using the raster-colorizer.

**Comment by Scarysize** [comment]
Thanks for the update on the issue, I left a comment at the corresponding issue in the mapbox-gl-js repo.

**Comment by lucaswoj** [comment]
Merged into https://github.com/mapbox/mapbox-gl-js/issues/3889
