### ISSUE TITLE
Write an explanation and include a picture of each layer type in the style spec docs

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#479]
Right now we don't explain layer types in narrative text. They have names and properties and one can infer from those, but we should be more explicit:

![2016-08-16 at 10 42 am](https://cloud.githubusercontent.com/assets/32314/17703013/2c3aa082-639e-11e6-9dbd-b6f4166261c3.png)

**Comment by 1ec5** [comment]
This would be helpful for the Mapbox iOS SDK, since by design, symbols without documentation comments are completely excluded from documentation, as if they don’t exist.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4123
