### ISSUE TITLE
Add paint property for icon image URL

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#485]
The `icon-image` property takes the name of an icon in the style’s `sprite` property, which means symbols can only wear the images provided by the style at design time. For parity with Apple’s MapKit framework and the Google Maps SDK, the mapbox-gl-native project and its SDKs support an alternative _annotation API_ that facilitates point and shape overlays in an imperative programming style. One of its distinguishing features is that you can “install” an arbitrary PNG data blob – whether read from a local or remote URL or rendered on the fly – and apply it to one or more point annotations. Whereas design-time sprites are often reused heavily, it’s very common in mobile applications for each individual annotation to wear a distinct image.

In order for the runtime styling API (which implements this style specification) to reach parity with the annotation API, we should add a paint property `icon-image-url` that can be set to a URL or URI. To support images rendered dynamically at runtime, data: URIs should also be allowed by the specification. It would be nice if HTTP(S) URLs could be used to display remote images in symbol layers, but this might be more complex to implement, considering that remote images would have to load asynchronously. Tokens should be supported, so that source data can determine the icon on a point-by-point basis.

I’m unsure whether this property should take precedence over `icon-image` if both are specified on the same layer.

/ref https://github.com/mapbox/mapbox-gl-native/issues/5626#issuecomment-232745438
/cc @mapbox/gl

**Comment by jfirebaugh** [comment]
Ref https://github.com/mapbox/mapbox-gl-js/issues/358. In particular https://github.com/mapbox/mapbox-gl-js/issues/358#issuecomment-159330509 proposes extending the `icon-image` property with a CSS-like `url(...)` syntax rather than introducing a new property.

**Comment by jfirebaugh** [comment]
Another approach -- one which I think we should follow even if we also add support for image URLs -- is to treat the icon set as an inline portion of the style itself rather than an independent resource requested by URL reference (c.f. https://github.com/mapbox/mapbox-gl-style-spec/issues/220#issuecomment-180024487) and then introduce icon CRUD operations to the runtime styling API.

**Comment by 1ec5** [comment]
> extending the `icon-image` property with a CSS-like `url(...)` syntax rather than introducing a new property

Given the discussions around token defaults in #104, we probably wouldn’t want to introduce a mini-language syntax that would break compatibility with existing `icon-image` usage. An object with a `url` property would be more consistent with the proposals in #104.

**Comment by kkaefer** [comment]
> Another approach -- one which I think we should follow even if we also add support for image URLs -- is to treat the icon set as an inline portion of the style itself rather than an independent resource requested by URL reference (c.f. #220 (comment)) and then introduce icon CRUD operations to the runtime styling API.

This makes sense and mirrors the way we handle GeoJSON and TileJSON data.

**Comment by lucaswoj** [comment]
Closing in favor of mapbox/mapbox-gl-js#2059 & mapbox/mapbox-gl-style-spec#220
