### ISSUE TITLE
diffStyle doesn't respect refs

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-style-spec#486]
The diffStyle utility cannot handle styles with refs. For example:

previous style:

``` js
  { "id": "building-shadow", ...},
  { "id": "building-fill", "ref": "building-shadow", ...}
```

next style:

``` js
  // (has neither building-fill nor building-shadow)
```

diffStyle:

``` js
commands
[
  // ...
  {"command": "removeLayer", "args": ["building-shadow"]},
    // map.removeLayer("building-shadow") also removes the "building-fill" layer.
  {"command": "removeLayer", "args": ["building-fill"]},
  // throws error: There is no layer with this ID
]
```

see: [map.removeLayer()](https://github.com/mapbox/mapbox-gl-js/blob/072f8cdc34b729c1b5956ca622bb01d1e716af4e/js/style/style.js#L446) for how it handles removing layers with refs.

**Comment by vicapow** [comment]
I'm not able to find a good way to implement style diffing with refs  😞 Removing ref layers is straightforward but updating / adding layers that may be referenced by other layers is difficult with the current mapbox API commands available. For example, `diffStyle`'s current implementation relies on removing and adding layers to "move" layers but when a referenced layer is removed, all the layers that reference it are removed, too.

I haven't found any examples of this but does anyone know if "refs" can be nested indefinitely? That would also complicate things.

I wrote some tests for these cases but I haven't added them to the branch because I still haven't found a good solution. Here they are for reference:

``` js
    t.deepEqual(diffStyles({
        layers: [{ id: 'a' }]
    }, {
        layers: [{ id: 'a' }, { id: 'b' }, { id: 'c', ref: 'b'}]
    }), [
        { command: 'addLayer', args: [{ id: 'b' }, undefined] },
        { command: 'addLayer', args: [{ id: 'c', ref: 'b' }, undefined] }
    ], 'add a layer');
```

**Comment by jfirebaugh** [comment]
I think we want to implement https://github.com/mapbox/mapbox-gl-js/issues/1393 (and the equivalent change in gl-native), making refs an internal implementation detail, and remove them from the style specification.

**Comment by vicapow** [comment]
fwiw, we came up with a solution for our use case by creating an `expandRefs` function to eliminate refs before passing them off to `diffStyles`.

**Comment by jingsam** [comment]
I agree to remove `ref` from the style specification, which make it like a program language. Remember the `constants` ever been in the style specification, no one miss them!

**Comment by jfirebaugh** [comment]
We're proceeding with the "remove refs" approach.
