### ISSUE TITLE
Add z-offset / levitation property

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-style-spec#488]
There are times when it would be useful to raise layers or features above other features on a map. For these cases, there should be a z-offset property:

![screen shot 2016-09-01 at 3 38 46 pm](https://cloud.githubusercontent.com/assets/108094/18181662/3a4fe010-705a-11e6-8a79-f587a03c9700.png)

It makes to have these properties use the same units as `extrusion-height` and `extrusion-min-height` rather than the units used by existing x/y offset and translate properties. For that reason, we'd need a add new property instead of introducing another element in existing offset/translate arrays.

z-offset would be useful for all layer types. If applied to a layer with extrusions, z-offset would offset the entire extrusion layer (effectively moving up both min and max heights.

Two questions:
1. What would happen when the map is not pitched?
   ![screen shot 2016-09-01 at 3 42 33 pm](https://cloud.githubusercontent.com/assets/108094/18181740/b81590c6-705a-11e6-903f-1fe6ca1a1c68.png)
2. Some map designers might expect or desire the option to let raised features cast shadows. Would something like this be technically possible?

![screen shot 2016-09-01 at 3 43 43 pm](https://cloud.githubusercontent.com/assets/108094/18181780/e8e45e76-705a-11e6-90f2-98bc2c657fed.png)

**Comment by jfirebaugh** [comment]
Duplicate of https://github.com/mapbox/mapbox-gl/issues/6?

**Comment by samanpwbb** [comment]
moved comment to https://github.com/mapbox/mapbox-gl/issues/6#issuecomment-244193192

**Comment by rvdende** [comment]
has this been implemented? It should be quite simple to do right? just a z value on addLayer?

**Comment by lbud** [comment]
@fluentart it has not been implemented. Further discussion has been moved to https://github.com/mapbox/mapbox-gl-js/issues/3993; one of several complications standing in the way is https://github.com/mapbox/mapbox-gl-js/issues/4134.
