### ISSUE TITLE
Add "line-dasharray-origin" property

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-style-spec#489]
It's common in vector editing tools to offset the origin point in a dasharray. Here's an example in inkscape:

![screen shot 2016-09-02 at 12 27 19 pm](https://cloud.githubusercontent.com/assets/108094/18210875/a824f126-7108-11e6-9948-36991aa27dd6.png)

Changing that value offsets the whole array. 

This property would be really useful when animating dasharrays. For example, a function like this would rotate the lines in the dasharray continuously:

``` js
  var origin = 0;
  setInterval(function() {
    map.setPaintProperty('layerid', 'dasharray-origin', origin);
    origin = origin + 1;
  }, 300);
```

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4126
