### ISSUE TITLE
Add symbol-placement: fill-area

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-style-spec#491]
A new `symbol-placement` value called `fill-area` would be useful in more stylized maps, for hand-placed looking hillshades and trees. For example of the kind of effect I'm after, see https://www.mapbox.com/bites/00099/ or https://www.mapbox.com/blog/super-mario-with-studio/. Here's how it would work:

![fill-area](https://cloud.githubusercontent.com/assets/108094/18447801/30b2a3ea-78f6-11e6-9586-10eeb8037069.png)

**Comment by ajashton** [comment]
What happens when you zoom?

Seems like there's some overlap with https://github.com/mapbox/mapbox-gl-style-spec/issues/427

**Comment by samanpwbb** [comment]
More icons would appear as you zoom to fill space. The advantage of this over #427 is that there'd still be symbol collision detection, and we'd never render partial symbols.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4127
