### ISSUE TITLE
Add test that fails if reference/v8.min.json is not up to date

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#494]
If you make changes to the reference, and forget to rebuild the minified source, it should be a CI failure, not a cryptic error in a downstream module that uses v8.min.json.

cc @boundsj

**Comment by scothis** [comment]
What's the rational for keeping the minified resources committed in the repo instead of creating them at publish time? The [commit that introduced the minified files](https://github.com/mapbox/mapbox-gl-style-spec/commit/f9e1c8a2ce311d47b80ee0bdccffae902db52c15) doesn't offer any detail as to why.

**Comment by jfirebaugh** [comment]
There isn't a publish step involved when mapbox-gl-style-spec is used in mapbox-gl-js.

**Comment by tmcw** [comment]
I have the same question as @scothis: when we publish mapbox-gl-js, there is a `.min.js` file generated that minifies dependencies like this one. Seeing our require tree, any kind of browserify application that does `require('mapbox-gl-style-spec')` requires both min & non-min versions of every style version, and then goes through uglifyjs and has duplicate code as a result.

**Comment by jfirebaugh** [comment]
Yes, and every version (v6, v7, v8). I don't see this as an issue -- if a package wants a minimal version, it should do what gl-js does: `require('mapbox-gl-style-spec/reference/latest.min')`. Minimizing the bundle size is exactly the reason that the `.min.js` file exists in the first place.

**Comment by tmcw** [comment]
Unfortunately, that isn't the only way that Studio uses the style spec. For instance, when we validate styles: we could sub-require validate_style.js, but that [requires ../](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/lib/validate_style.js) so we're back to the same problem.

**Comment by jfirebaugh** [comment]
`require('mapbox-gl-style-spec/lib/validate_style.min')`

**Comment by tmcw** [comment]
Okay, how about migrating styles? Not seeing a `migrate.min.js`.

Still not understanding the logic: we include min.js to minimize _uncompressed_ bundle size of packed modules that depend on this one? When is that a priority?

**Comment by jfirebaugh** [comment]
https://github.com/mapbox/mapbox-gl-js/commit/84d20638c91bfc948d1c8d7d8745f222c801d145 makes this unnecessary.
