### ISSUE TITLE
Document that`text-max-width` property is only for `symbol-placement: point`

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#496]
https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-max-width

Currently, all text with `symbol-placement: line` gets assigned `text-max-width: 0` and does not wrap.

**Comment by jfirebaugh** [comment]
Not working for `symbol-placement: line, text-rotation-alignment: map/auto` makes sense, but it may just be a bug that it doesn't work for `symbol-placement: line, text-rotation-alignment: viewport`.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4128
