### ISSUE TITLE
Create consistent SDK support naming convention

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#498]
Why "Base _support_" but not "Data-driven styling _support_" or "`auto` value _support_"?

Some good examples to follow:
- http://node.green/
- http://caniuse.com/#search=es6

**Comment by jfirebaugh** [comment]
It's a compromise: "support" is implied for every row in the table; repeating it for every row adds noise. But "Base" on its own is unclear.

If you have a concrete proposal for an alternative, happy to entertain it. Otherwise I think this is fine as is.

**Comment by lucaswoj** [comment]
I will submit a PR with a concrete proposal.
