### ISSUE TITLE
Allow one property to require another property to have an array of possible values

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-style-spec#504]
There's a problem with `icon-text-fit-padding`. It [says that it requires `icon-text-fit`](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v8.json#L677), but in fact it requires `icon-text-fit` to have any of its possible values other than `none`. With `"icon-text-fit": "none"`, `icon-text-fit-padding` is no good.

Looks like [there is existing syntax](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v8.json#L452) for one property requiring that another property have _a specific value_; but not for this case, where one property requires that another property have _one of several values_.

Can we add the ability for an object within `"requires"` to take an array of possibilities as its value?

For example, to address the root issue with `icon-text-fit-padding`:

``` json
"requires": [ 
  "icon-image",
  {
    "icon-text-fit": ["both", "width", "height"]
  },
  "text-field"
]
```

cc @samanpwbb

**Comment by jfirebaugh** [comment]
👍 

I know of only two current uses of `requires`, both of which can be updated to support this: Mapbox Studio and [this doc generation code](https://github.com/mapbox/mapbox-gl-style-spec/blob/f1d3912709dc0749ee7d7af324739b07fa9ef726/docs/_generate/item.html#L27-L38).

**Comment by davidtheclark** [comment]
I can work on a PR for this. But I do have some questions upfront:
- How do you like to handle changes like this? Do we update the apps first (Studio) to anticipate the change, or just release the new spec? (Or something else?)
- Is this going to require a major release? Or would it be considered a bug fix since `icon-text-fit-padding` would not have worked with ``"icon-text-fit": "none"` anyway?

**Comment by jfirebaugh** [comment]
I'd consider this a patch bump. We've accumulated other changes that deserve a minor version bump though, from #493, so I think the next version should be 8.9.0.

cc @scothis for the Studio coordination question.

**Comment by 1ec5** [comment]
> I know of only two current uses of `requires`, both of which can be updated to support this: Mapbox Studio and [this doc generation code](https://github.com/mapbox/mapbox-gl-style-spec/blob/f1d3912709dc0749ee7d7af324739b07fa9ef726/docs/_generate/item.html#L27-L38).

Also [this iOS/macOS SDK documentation generation code](https://github.com/mapbox/mapbox-gl-native/blob/6aa00afd317762afbec7add23ff6be735b5765ac/platform/darwin/src/MGLStyleLayer.h.ejs#L67-L70) ([more here](https://github.com/mapbox/mapbox-gl-native/blob/6aa00afd317762afbec7add23ff6be735b5765ac/platform/darwin/scripts/generate-style-code.js#L101-L112)).

**Comment by davidtheclark** [comment]
@1ec5 I will get a PR over there this afternoon.
