### ISSUE TITLE
"ems" and "em" both listed as units

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-style-spec#507]
`text-offset` [has `"ems"`](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v8.json#L1123); while `text-max-width`, `text-line-height`, and `text-letter-spacing` [have `"em"`](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v8.json#L904).

Is there a reason for this difference, or is it an oversight? Happy to correct with a PR if so.

**Comment by jfirebaugh** [comment]
Yes,  "ems" is correct, consistent with "pixels" and "degrees".
