### ISSUE TITLE
text-field documentation doesn’t mention token syntax

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#519]
The [`icon-image`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-image) documentation starts out with “A string with {tokens} replaced,” yet the [`text-field`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-field) documentation doesn’t mention this syntax. (Are there any other properties that make use of this syntax?)

/cc @jfirebaugh

**Comment by 1ec5** [comment]
Somehow we should also point out that special tokens are recognized, like we do in the [Filter](https://www.mapbox.com/mapbox-gl-style-spec/#types-filter) documentation. I’m not sure if `{$id}` and `{$type}` are supported, but `point_count` apparently is, per https://github.com/mapbox/mapbox-gl-native/issues/6609#issuecomment-251992910.

**Comment by jfirebaugh** [comment]
There aren't any special tokens -- `{$id}` and `{$type}` aren't supported, and from the perspective of token interpolation `{point_count}` is just a normal property. When features are clustered, they generate new features, which have certain properties. The [clustering documentation](https://www.mapbox.com/mapbox-gl-style-spec/#sources-geojson-cluster) is where these should be documented.

**Comment by lucaswoj** [comment]
Fixed!

**Comment by ericjames** [comment]
What happens when a {token} doesn't exist?  It looks like it just fails for me `Uncaught ReferenceError: TYPE is not defined`
