### ISSUE TITLE
Documentation doesn’t cross-link required properties

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#520]
When a property such as [`text-font`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-font) requires another property to be set (in this case, `text-field`), the HTML documentation displays the property unlinked. The required property should be cross-linked for easier navigation.

/cc @davidtheclark

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4131
