### ISSUE TITLE
Missing css/site.css

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-style-spec#521]
When I run `jekyll serve -w`, the site looks like this:
![image](https://cloud.githubusercontent.com/assets/1522494/19219265/2069a49c-8e41-11e6-9547-66acc5af216b.png)

I checked that the site is trying to retrieve site,css from `http://localhost:4000/css/site.css`, which should be `https://122e4e-mapbox.global.ssl.fastly.net/css/site.css`. It seems that `jekyll serve` overwrites `url` in `_config.yml

Windows 10
jekyll 3`

**Comment by jfirebaugh** [comment]
Not reproducible for me. Could be Windows specific; I'm afraid you're going to have to debug this on your own.
