### ISSUE TITLE
“light” is undocumented

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-style-spec#522]
![image](https://cloud.githubusercontent.com/assets/1522494/19225925/da484a18-8ed6-11e6-9659-ee50acb78c2b.png)

**Comment by 1ec5** [comment]
This root property was added in #495. Indeed, it’s missing a `doc` property in the JSON schema. Until #495, each root property in the schema had specific properties defined, like `type`, `doc`, and `sdk-support`. `light` instead has properties that correspond to properties in the resulting JSON stylesheet. It should follow the model of `transition`: `$root.light.type` should be set to `light`, then `light` should be a property at the top level, set to the object that `$root.light` is currently set to.

/cc @lbud

**Comment by 1ec5** [comment]
A fix is ready in #542.
