### ISSUE TITLE
Where is the property of ‘sprite-image’？

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-style-spec#523]
![image](https://cloud.githubusercontent.com/assets/1522494/19226614/e14874b0-8edf-11e6-9811-5a6fe03efcba.png)

 As I know, `sprite` is required if any layer uses `icon-image`, `fill-pattern`, `line-pattern` properties.

**Comment by jfirebaugh** [comment]
> `sprite` is required if any layer uses `icon-image`, `fill-pattern`, `line-pattern` properties.

Yes, and also `background-pattern`. Want to send a PR correcting this?

**Comment by jfirebaugh** [comment]
Fixed in #531.
