### ISSUE TITLE
Support referencing one constant in another constant

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#53]
Can we support referencing one constant in another constant?

E.g.
      `"place-halo": "#faf3ed  ",`
     `"country-halo": "place-halo"`

Or

    `"land": ""#ebe5e0",
    `"country-halo": { "lighten": ["land", 10] }`

(The syntax in the second example is not valid – I just made it up to demonstrate that the ability to reference other constants could be useful once we have color functions: https://github.com/mapbox/mapbox-gl-style-spec/issues/38)

**Comment by jfirebaugh** [comment]
@nickidlugash Is this still needed given current UI technology?

**Comment by nickidlugash** [comment]
@jfirebaugh the current UI is not yet there to support something like this (this is basically the idea behind constant transforms, but it is not implemented yet). I think we're pretty set on this eventually being something the UI will handle though, so we can close here.

**Comment by nickidlugash** [comment]
> I think we're pretty set on this eventually being something the UI will handle though, so we can close here.

Um...maybe not? https://github.com/mapbox/mapbox-gl-style-spec/issues/38#issuecomment-70960411

**Comment by jfirebaugh** [comment]
Haha... oops, I guess there's a downside to merging the history. This bug was closed by a commit from the lint repository that fixed https://github.com/mapbox/mapbox-gl-style-lint/issues/53.

**Comment by jfirebaugh** [comment]
RIP constants.
