### ISSUE TITLE
‘text-justify‘ option may not appropriate for rtl language, like Arabian 

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-style-spec#533]
![image](https://cloud.githubusercontent.com/assets/1522494/19266911/618def52-8fde-11e6-81c2-14140e753403.png)

Suggest use `start` `center` `end`.

**Comment by jfirebaugh** [comment]
I don't think it makes sense to make the behavior of `text-justify` dependent on the directionality of the text unless we also provide directionality-dependent values for `text-anchor`.
