### ISSUE TITLE
Chinese version of style spec

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-style-spec#535]
I have finished the translation of this spec in Chinese, checkout this: https://github.com/jingsam/mapbox-gl-style-spec/blob/mb-cn-pages/reference/v8.json

I am also trying to generate a HTML version, almost finished. check this:
![image](https://cloud.githubusercontent.com/assets/1522494/19283358/10ee067c-9024-11e6-9f5b-6993ef4eb90f.png)

**Comment by jingsam** [comment]
@jfirebaugh @peterqliu @willwhite I have finished all of the translations, checkout this: https://jingsam.github.io/mapbox-gl-style-spec/. What do you think about it?

**Comment by hanchao** [comment]
nice work

**Comment by lucaswoj** [comment]
This is awesome 😄
