### ISSUE TITLE
Links to special types are broken

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#543]
The [`sources`](http://127.0.0.1:4000/mapbox-gl-style-spec/#root-sources) property’s link to the “sources” type is broken; it should point to [this section](http://127.0.0.1:4000/mapbox-gl-style-spec/#sources) with the anchor `#sources` rather than `#type-sources`. A similar issue affects links to the [`transition`](http://127.0.0.1:4000/mapbox-gl-style-spec/#transition) type and also the `light` type once #542 lands. (In any case, the `sources` root property should actually have `"type": "array", "value": "sources"` rather than `"type": "sources"`.)

/cc @lbud

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4133
