### ISSUE TITLE
"line-cap": "round" + "line-dasharray": [1, 1] should produce circles

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#546]
The combination of `"line-cap": "round"` and `"line-dasharray": [1, 1]` should produce a line consisting of circles with diameter equal to the line width, spaced one line width from each other.

Instead, it produces this:

![image](https://cloud.githubusercontent.com/assets/98601/19580753/3aec50ea-96dd-11e6-81c6-06f84eb1be5e.png)

**Comment by jingsam** [comment]
I think this is intended feature, the spec says:

> round
> A cap with a rounded end which is drawn **beyond the endpoint of the line** at a radius of one-half of the line's width and centered on the endpoint of the line.

So when "line-dasharray": [1, 1], it renders like this:
![image](https://cloud.githubusercontent.com/assets/1522494/19584232/7ead2f28-9775-11e6-9f29-b1adfcf540b0.png)

Want to get a a line consisting of circles, try to set "line-dasharray": [0, 1]

![image](https://cloud.githubusercontent.com/assets/1522494/19584270/b9dc81f2-9775-11e6-8975-fdea0c89994e.png)

**Comment by jfirebaugh** [comment]
Yes, I'm suggesting we should change the definition. The existing definition isn't what people expect.

**Comment by jingsam** [comment]
I think we should keep this behaviour consistent with the definition of [stroke-linecap](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap) in SVG or [linecap](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineCap) in Canvas. That is what a web developer would expect.

**Comment by jfirebaugh** [comment]
Good point. I just confirmed that the current definition is consistent with SVG.
