### ISSUE TITLE
Case and diacritic folding for filter operations

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#548]
As discussed in mapbox/mapbox-gl-native#6781, it can often be necessary for a filter to perform a case-insensitive or diacritic-insensitive comparison. Variations on the existing operators should be added to support these options.

Here’s an example design (but by no means the best):

``` json
[
  {
    "operator": "in",
    "case-sensitive": false,
    "diacritic-sensitive": false,
  },
  "key",
  "value 1",
  "value 2"
]
```

Implementing case-insensitive comparisons should be trivial on all the platforms supported by Mapbox GL. On the other hand, while there are fine options for diacritic folding on the native platforms, JavaScript would have to rely on a library for diacritic-insensitive comparisons.

/cc @incanus @lucaswoj @jfirebaugh

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4136
