### ISSUE TITLE
Display `minimum` and `maximum` properties in published docs

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-style-spec#551]
The style spec includes `minimum` and `maximum` for some properties ([example](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v8.json#L1707)) but these don't display in the [published docs](https://www.mapbox.com/mapbox-gl-style-spec/#paint-fill-extrude-height). `minimum` and `maximum` properties should be displayed in our docs.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4138
