### ISSUE TITLE
[BREAKING] Remove fill-extrude-height and fill-extrude-base; move to a separate fill-extrusion type

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-style-spec#554]
We're going to remove the `fill-extrude-height` and `fill-extrude-base` properties and instead create a separate `fill-extrusion` type.

Unfortunately this is a breaking change, but it's the right way to maintain flexibility for future 3D types in the spec and to keep certain logical patterns in our renderers.

As it stands, fill layers and extruded fill layers have the following differences:
- fill layers render with per-feature opacity; extruded fill layers render with per-layer opacity
- extruded fill layers do not support `fill-outline-color`
- extruded fill layers utilize a different bucket type, and switching between those causes problems (https://github.com/mapbox/mapbox-gl-js/issues/3386); maintaining a 1:1 spec type - bucket type - render type is much cleaner
- flat fill layers are rendered at a specified color, whereas the tops of extruded fill layers, even if they are flat features, are colored depending on light settings, and don't match `fill-color` exactly

Moreover, creating separate layer types will leave room for flexibility in deciding how to handle [extruded texture compositing](https://github.com/mapbox/mapbox-gl-style-spec/issues/545).

This will be a reversion to the way we originally designed extrusions in https://github.com/mapbox/mapbox-gl-style-spec/issues/456. (In happy news, this actually will make it easier to implement extrusions in gl-native once it supports property functions, since I more or less did it this way this summer…)

This change will go into effect ASAP so as to minimize the damage. `fill-extrude-height` and `fill-extrude-base` were introduced in Mapbox GL JS v0.26.0; they will be removed in favor of a `fill-extrusion` type in Mapbox GL JS v0.27.0, to be released next week. ~~Layers created with these properties **will render the same** but will just require a bit of layer property renaming~~ <- rendering will change due to https://github.com/mapbox/mapbox-gl-js/issues/3385 (extrusion heights will now be specified in meters instead of magicnumbers).

cc @mapbox/gl @mapbox/labs @mapbox/cartography-cats @mapbox/support

🙏 
### To do:
- [x] mapbox-gl-style-spec PR https://github.com/mapbox/mapbox-gl-style-spec/pull/555
- [x] mapbox-gl-js PR https://github.com/mapbox/mapbox-gl-js/pull/3487
- [x] mapbox-gl-test-suite PR https://github.com/mapbox/mapbox-gl-test-suite/pull/155
- [x] mapbox-gl-shaders PR (renames) https://github.com/mapbox/mapbox-gl-shaders/pull/29
- [x] Revise blog post (not linking to private repo; PR open and waiting for the release)
- [x] Revise documentation/examples https://github.com/mapbox/mapbox-gl-js/pull/3488 + open PR in help docs *
- [x] Address https://github.com/mapbox/mapbox-gl-js/issues/3385
- [ ] Release v0.27.0
- [ ] Announce, beg for forgiveness

\* There are some Mapbox demos floating around (embedded in blog posts, etc) that use `fill-extrude-height`/`fill-extrude-base` and link to either a prior dev build or v0.26.0; I think it's fine if those stay as they are.

**Comment by jfirebaugh** [comment]
☝️  That's a lot of linked issues! Thanks for hitting this @lbud.

**Comment by ryanbaumann** [comment]
@lbud this is awesome fix before extrusions are heavily adopted.  Thank you!
