### ISSUE TITLE
Requirements that are always satisfied should be removed

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-style-spec#560]
For example: `line-translate-anchor` requires that `line-translate` have a value. But `line-translate` has a `default` set to `[0, 0]` — meaning that *it will always have a value*. Because this explicit requirement is actually always satisfied, it is meaningless and kind of confusing, right?

I'm working on Studio's style editor, deciding when to disable forms, and ran into this confusion. There seem to be some other situations like this, as well, besides the `line-translate-anchor` example.

If others agree that these always-satisfied requirements should be removed, I can work on a PR.

cc @tmcw (we chatted about this)

**Comment by davidtheclark** [comment]
A lot of properties require `text-field`, which has a `default` of `""`. That causes some trouble, unless we add more logic to the requirement specifying that the required value _must not be_ something. And that gets at #513.

**Comment by jfirebaugh** [comment]
The intent in these cases is to require a non-default value. `line-translate-anchor` doesn't do anything if the translation is zero. `text-rotation-alignment` doesn't do anything if there's no text. Etc.

**Comment by davidtheclark** [comment]
`line-miter-limit` requires that `line-join` be `"miter"`, which is also the default value for `line-join`. If we disable `line-miter-limit` when `line-join` has its default value, it will never be enabled.

This would mean, then, that there's also an implicit intent that the non-default-value expectation only applies to requirements that are bare strings instead of objects, right? That seems like another sign that the data structure of requirements is over-abbreviated.

**Comment by davidtheclark** [comment]
Looks like this is probably tangled up with #351.
