### ISSUE TITLE
Describe dynamic defaults

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-style-spec#561]
My search isn't turning up a discussion of this before (maybe I'm missing it?) ...

It seems right now that the default value of fill-outline-color is "informally" defined as the current value of `fill-color`. It would be nice for formally define this relationship.

Maybe `fill-outline-color` will go away (#240). Will this problem go away with it?

**Comment by jfirebaugh** [comment]
We had [a similar situation with `{text,icon}-rotation-alignment`](https://github.com/mapbox/mapbox-gl-style-spec/issues/235), which we resolved by adding an [`auto` default enum value](https://github.com/mapbox/mapbox-gl-style-spec/pull/493). That type of solution doesn't really work for non-enum valued properties like `fill-outline-color` however.

> Maybe `fill-outline-color` will go away (#240). Will this problem go away with it?

It would, yes. Another reason to hasten `fill-outline-color`'s demise.

**Comment by lucaswoj** [comment]
We have documented the `fill-outline-color` in the docs and plan to address this problem by removing `fill-outline-color`
