### ISSUE TITLE
The lack of ecosystem-wide support for data-driven styling is not prominent enough 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#568]
Users are often confused about this. We should make sure that the lack of ecosystem-wide support for data-driven styling is more prominently documented. 

Some ideas

 - add a `data-driven styling` row to every style property, even those that don't have support on any platform
 - make the language about data-driven styling support more visually distinct ⚠️

**Comment by jfirebaugh** [comment]
⇢ #567
