### ISSUE TITLE
Include Static API rendering in sdk-support properties

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-style-spec#569]
In addition to our client side SDKs we also have a server side renderer with the [Mapbox Static API](https://www.mapbox.com/api-documentation/#static). Unlike our SDKs, the static support is not versioned, the property/feature is either supported or not.

```
"sdk-support": {
  "basic functionality": {
    "js": "0.10.0",
    "ios": "2.0.0",
    "android": "2.0.1",
    "static": true
  }
}
```

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4140
