### ISSUE TITLE
Add moveLayer operation to diffStyles

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-style-spec#577]
Currently, when a layer is moved, diffStyles produces a `removeLayer`/`addLayer` pair.  Replacing this with `moveLayer` would better enable the use of the `{Map,Style}#moveLayer` methods in GL JS ( See also https://github.com/mapbox/mapbox-gl-js/issues/3649 )

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4142
