### ISSUE TITLE
Nine-part resizable images

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#581]
As part of moving style images inline (#220), we should add support for resizable images, also known as _border images_ in [CSS](https://www.w3.org/TR/css3-background/#border-images) and on [Qt](http://doc.qt.io/qt-5/qml-qtquick-borderimage.html), _stretchable images_ on [iOS](https://developer.apple.com/reference/uikit/uiimage#1658362), _nine-part images_ on [macOS](https://developer.apple.com/reference/appkit/1526394-nsdrawninepartimage), and _nine-patch images_ on [Android](https://developer.android.com/guide/topics/graphics/2d-graphics.html#nine-patch).

In combination with the `icon-text-fit` property added in #461, a resizable image would automatically resize to fit a label, but we’d be able to avoid distorting its corners or any outline baked into it. The “corner” parts of the image would remain as-is regardless of the image’s rendered size, while “edge” parts of the image could be either stretched or repeated, depending on the use case.

Just to kick things off, the proposed syntax below is loosely based on CSS3’s `border-image` properties:

```json
{
  "de-federal": {
    "width": 6,
    "height": 6,
    "x": 824,
    "y": 642,
    "pixelRatio": 2,
    "slice": [5, 5, 5, 5],
    "repeat": ["stretch", "repeat"]
  }
}
```

This feature would allow styles such as Mapbox Streets to consolidate several style images that currently differ only in the number of digits that fit within them, and these images could be much smaller, making the overall sprite sheet more compact. Some `reflen`-specific images would still be required for exotic shapes, such as the Interstate and U.S. Route shields.

/cc @mapbox/cartography-cats @mapbox/gl

**Comment by cammace** [comment]
I've been running into this distortion issue with the images i've been adding to the map during runtime. It would be great to also be able to use [`icon-color`](https://www.mapbox.com/mapbox-gl-style-spec/#paint-icon-color) on the nine-patch images.

**Comment by kkaefer** [comment]
Might be subsumed by https://github.com/mapbox/mapbox-gl-style-spec/issues/222?

**Comment by 1ec5** [comment]
Not necessarily. While both nine-part images and a truly scalable image format have some overlap of use cases (especially for highway shields), there’s a lot of good tooling and native platform support around nine-part images that likely won’t be compatible with any custom image format we develop. So nine-part images would be desirable for better platform integration at least.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4143
