### ISSUE TITLE
Specify what happens when evaluating a categorical function input that's not in the domain

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#582]
E.g. what does `{"type": "categorical", "property": "p", "stops": [["foo", 0]]}` evaluate to for the property value "bar"?

**Comment by davidtheclark** [comment]
I think this issue and #480 are vital for making categorical functions seem "usable". I'm not sure I'd feel very comfortable shipping a public DDS UI in Studio without them. (cc @mapbox/appbox)

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4144
