### ISSUE TITLE
Use words instead of symbols

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#584]
Replace ![image](https://cloud.githubusercontent.com/assets/98601/20683177/d3f5ea44-b55f-11e6-8153-d88128b80f37.png) and ![image](https://cloud.githubusercontent.com/assets/98601/20683188/dc589cea-b55f-11e6-883b-0d55346e81ed.png) with words ("continuous" and "discrete"?).

You can't search for symbols to see what properties use which type, and the meaning isn't clear from the symbol.

**Comment by davidtheclark** [comment]
Why introduce "continuous" and "discrete" into the mix when there's already "interpolated" and "piecewise-constant"? My head is being tied into knots by the number of "function types" 
༼ ºººººل͟ººººº ༽

**Comment by jfirebaugh** [comment]
Yeah, when I wrote that I forgot that we already had the terms "interpolated" and "piecewise-constant". We should be consistent and use one set or the other everywhere.

I have a proposal brewing to rationalize the current set of function types into something more understandable. Stay tuned.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4145
