### ISSUE TITLE
Non-categorical functions with string stops?

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#587]
How does this function work? E.g. what is the evaluated value for a feature whose `p` property is "fuzz"?

```
{
  "type": "exponential",
  "property": "p",
  "stops": [
    ["foo", 0],
    ["bar", 100]
  ]
}
```

What about this one? Is it valid?

```
{
  "type": "interval",
  "property": "p",
  "stops": [
    ["a", 0],
    ["å", 5],
    ["b", 10]
  ]
}
```

cc @lucaswoj

**Comment by lucaswoj** [comment]
String domains only make sense for `categorical` functions. `exponential` and `interval` functions require a numeric domain.
