### ISSUE TITLE
Why are stop values for property functions allowed to be an array?

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#595]
Why is array included in [this list](https://github.com/mapbox/mapbox-gl-style-spec/blob/d91d3cd4bce435a75cebf8fd17501bfadfa046e4/lib/validate/validate_function.js#L136-L138)? Do we really want to allow, e.g.:

```
{
  "type": "categorical",
  "property": "p",
  "stops": [
    [[0, 1], 0],
    [[2, 3], 10]
  ]
}
```

This seems like a crazy edge case that we shouldn't support.

cc @lucaswoj @ansis

**Comment by ansis** [comment]
I agree it shouldn't be supported

**Comment by lucaswoj** [comment]
This was a mistake on my part. The intention was to allow stops for range values, not domain values.
