### ISSUE TITLE
Are categorical zoom-and-property functions allowed?

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#600]
Categorical zoom functions are clearly not useful (#599), but what about categorical zoom-and-property functions?

As I understand it, the zoom portion of a zoom-and-property function is always exponentially interpolated, regardless of the `"type"`.

cc @lucaswoj @ansis

**Comment by lucaswoj** [comment]
This has been clarified as of  #604
