### ISSUE TITLE
Are "identity" zoom functions allowed?

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#603]
```
    {
      "id": "fill",
      "type": "fill",
      "source": "source",
      "source-layer": "layer",
      "paint": {
        "fill-opacity": {
          "type": "identity"
        }
      }
    }
```

Is this allowed?

**Comment by lucaswoj** [comment]
I can't think of a reason why we shouldn't allow this unless it adds implementation complexity.

**Comment by jfirebaugh** [comment]
It will add four additional rows to #604, which translates to implementation complexity for gl-native.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4151
