### ISSUE TITLE
Exhaustively enumerate allowable function types

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#604]
We've accumulated a proliferation of species of function. In order to implement them all correctly in a strongly typed language, we're going to have to be stricter and more explicit than we have been so far in terms of enumerating what kinds of function are allowed in what situations. I've been trying to work it out and here's what I've come up with.

The allowed kinds of function depend on the _style property_. In particular, on whether the style property is _interpolated_ or _piecewise-constant_, and whether it's enabled for data-driven styling.

#### interpolated, non-data-driven
* Exponential zoom
* Interval zoom

#### piecewise-constant, non-data-driven
* Interval zoom

#### interpolated, data-driven
* Identity property
* Exponential zoom
* Exponential property, numeric domain type
* Exponential zoom-and-property, numeric domain type
* Interval zoom
* Interval property, numeric domain type
* Interval zoom-and-property, numeric domain type
* Categorical property, string domain type
* Categorical property, numeric domain type

#### piecewise-constant, data-driven
* Identity property
* Interval zoom
* Interval property, numeric domain type
* Interval zoom-and-property, numeric domain type
* Categorical property, string domain type
* Categorical property, numeric domain type

The above list assumes that "No" is the answer to all of the following:

* [Are identity zoom functions allowed?](https://github.com/mapbox/mapbox-gl-style-spec/issues/603)
* [Are categorical zoom functions allowed?](https://github.com/mapbox/mapbox-gl-style-spec/issues/599)
* [Are categorical zoom-and-property functions allowed?](https://github.com/mapbox/mapbox-gl-style-spec/issues/600)
* [Are exponential or interval domain types other than number allowed?](https://github.com/mapbox/mapbox-gl-style-spec/issues/587)
* [Are categorical domain types other than string and number allowed?](https://github.com/mapbox/mapbox-gl-style-spec/issues/595)
* [Are exponential functions allowed for piecewise-constant properties?](https://github.com/mapbox/mapbox-gl-style-spec/issues/601)

cc @lucaswoj @davidtheclark @ansis

**Comment by davidtheclark** [comment]
What is the difference between a *non-data-driven* interval zoom function and a *data-driven* interval zoom function, if interval zoom-and-property is also in the list? Same question applies to exponential zoom functions.

**Comment by jfirebaugh** [comment]
@davidtheclark That was a mistake, I removed the zoom variants from the "data-driven" categories.

**Comment by jfirebaugh** [comment]
Wait no, it wasn't a mistake. The "non-data-driven"/"data-driven" headings refer to whether or not a particular style property is data-driven, not categories of function type. If a style-property is enabled for data-driven styling, it still supports zoom functions.

**Comment by jfirebaugh** [comment]
⇢ #613
