### ISSUE TITLE
Allow boolean input values for property functions

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-style-spec#606]
Right now a boolean input value (the reference field value) for a property function is invalid: https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/lib/validate/validate_function.js#L133.

But this seems like a valid and not-uncommon use-case. E.g. "I am a grumpy groundskeeper and have a bunch of dots representing houses I oversee. Each house feature has a 'paid-for' property whose value is a boolean representing whether the house's monthly service has been paid for or not. I want the unpaid houses to be red, the paid houses to be blue."

Is there a reason to invalidate boolean input values?

**Comment by lucaswoj** [comment]
No reason I can think of. We should add this.

**Comment by jfirebaugh** [comment]
This will also require downstream changes in mapbox-gl-function [here](https://github.com/mapbox/mapbox-gl-function/blob/41c6724e2bbd7bd1eb5991451bbf118b7d02b525/index.js#L22), unless we revert https://github.com/mapbox/mapbox-gl-function/issues/19, which I'm arguing we should do in https://github.com/mapbox/mapbox-gl-js/issues/3717#issuecomment-264011926.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4152
