### ISSUE TITLE
Do we need min JSON files in gl-style-spec?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#609]
Split from #494

Right now gl-style-spec includes minified versions of the style spec, and requires/re-exports them in index.js. The rationale for this is, as far as I know, so that uncompressed Mapbox GL JS builds are smaller. There's no effect on compressed Mapbox GL JS sizes.

The side effects are:

- Any bundled application that calls `require('mapbox-gl-style-spec')` includes 2 copies of every reference JSON. They can avoid this by sub-requiring a specific style spec, or by requiring validate_style.min.js, but they cannot avoid this if they need migration or another feature that doesn't have a min-only require path.
- Node applications don't benefit and slightly lose out, because they keep 2 versions of every reference JSON in memory.
- The validate_style.js code is more complex because it works around minified references
- We have generated files in git history, making PRs a bit harder
- Since applications that don't want to waste space will need to sub-require modules, we're making any change to internal file naming structure a breaking change - whereas if `index.js` was a non-wasteful way to use this library, we could move `validate_style` if we wanted to rename lib to src, for instance, without a major breaking change.
- Small mistakes in requiring mapbox-gl-style-spec means requiring both min and not min: this [has already happened in gl-js](https://github.com/mapbox/mapbox-gl-js/issues/2997)

My 2c is that minified files don't pull their weight and we should remove them from mapbox-gl-style-spec. They introduce problems for real world applications while solving a problem that is, in my opinion, less important: reducing uncompressed GL JS bundles. If you need a small GL JS bundle, use the minified version or minify your bundle.

**Comment by jfirebaugh** [comment]
In addition to removing whitespace, the minified files also omit `doc`, `example`, and `sdk-support` properties. So I believe there is an effect on compressed Mapbox GL JS sizes. If you've empirically tested this and saw otherwise, let me know.

**Comment by jfirebaugh** [comment]
There's no good reason for `index.js` to include the minified versions. We can remove that, which would address the first two points.

**Comment by scothis** [comment]
In the case of Studio, we need the extra metadata that the min file drops, so that's of no help.

My initial reason for questioning the existence of the min files is that any web app sophisticated enough to require a json file from a npm package is also sophisticated enough to run it's own minifier and gzip the result.

Minified and gziped, the full v8 spec is 9K, while the min spec is 2.5KB. The gl-js dist is 131KB.

**Comment by jfirebaugh** [comment]
> any web app sophisticated enough to require a json file from a npm package is also sophisticated enough to run it's own minifier and gzip the result.

The issue with this is that validation code need access to a spec JSON object. In order to extract minification downstream, we'd also need to change the validation API so that the spec JSON dependency is an external dependency.

**Comment by jfirebaugh** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-js/commit/84d20638c91bfc948d1c8d7d8745f222c801d145 🎉
