### ISSUE TITLE
Zoom functions for light properties

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-style-spec#612]
The spec appears to permit zoom functions for light properties, and gl-js happily handles them correctly, however, the validator rejects zoom functions for light properties.

I assume the spec and gl-js is correct and the validator is wrong, but wanted to confirm before I submit a PR for the validator.

cc @lbud

**Comment by lbud** [comment]
@lucaswoj just merged a related PR today (https://github.com/mapbox/mapbox-gl-style-spec/pull/598) — @scothis does that fix it or are you seeing another issue?

**Comment by scothis** [comment]
Yep, that did the trick. Someday I'll learn to search more than just the open issues list before creating a new ticket.
