### ISSUE TITLE
Allow color space definition for transitioning colors

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-style-spec#62]
There are [many different ways](http://howaboutanorange.com/blog/2011/08/10/color_interpolation/) to interpolate or transition between two colors:

![screen shot 2014-06-20 at 2 39 07 pm](https://cloud.githubusercontent.com/assets/1577766/3346229/b363c950-f8c3-11e3-91c7-2e1e69c16af6.png)

By default, all colors are interpolated with the RGB color space. Should we allow a few other color spaces?

**Comment by jfirebaugh** [comment]
- https://github.com/mapbox/mapbox-gl-function/pull/26
- https://github.com/mapbox/mapbox-gl-js/pull/3245
- https://github.com/mapbox/mapbox-gl-style-spec/pull/515
- https://github.com/mapbox/mapbox-gl-native/pull/6442
