### ISSUE TITLE
Support arbitrary expressions in functions, filters, and cluster aggregators

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#630]
Let's continue the conversation from https://github.com/mapbox/mapbox-gl-function/issues/28 here 😄 

To summarize so far:

 - Arbitrary expression functions will make our filters, functions, and cluster aggregators more powerful & flexible 
 - Implementing arbitrary expressions will be challenging because they may need to run on the GPU 
 - We are leaning towards a lispy syntax comprised of nested arrays

**Comment by 1ec5** [comment]
Also, devising a workable GUI for arbitrary expressions may be a challenge.

**Comment by lucaswoj** [comment]
My mistake, https://github.com/mapbox/mapbox-gl-style-spec/issues/47 is a better place for this conversation.

I moved over your comment @1ec5 😄
