### ISSUE TITLE
Refactor the style validator to use an off-the-shelf format like JSON Schema

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#634]
Our ad-hoc JSON format that mixes validation logic & metadata can be tricky to work with.

Basing our validation on a tool like [JSON Schema](http://json-schema.org/documentation.html) would simplify and provide structure to our validation logic. It my also allow us to use some 3rd party validation, debugging, & documentation tools.

**Comment by jfirebaugh** [comment]
I think there are certain requirements that can't be captured in JSON Schema and will continue to require custom validation, but fewer than we have right now with our home grown schema.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4159
