### ISSUE TITLE
Eliminate the syntactic distinction between "paint" and "layout" properties

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#635]
The differences between "paint", "layout", and "top-level" properties are becoming increasingly nuanced. Without a firm knowledge of our implementation, it can be hard to reason about the behaviour of paint properties vs layout properties, especially in the context of data-driven styling. It is worth considering eliminating the syntactic distinction between "paint" and "layout" properties (as Studio does), instead providing documentation about the behaviour of each property.

**Comment by nickidlugash** [comment]
This sounds good generally, but just want to flag that it may make the definition of a `ref` sound more convoluted.

**Comment by lucaswoj** [comment]
@nickidlugash We're getting rid of `ref`s too 😄  As of now, `ref` is a no-op in GL JS.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4160
