### ISSUE TITLE
Support using feature filters with tiles from geojson-vt

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#640]
> For whatever reason geojson-vt generates vector tiles with geojson properties mapped to the `tags` property. This module used to check for `f.tags` and it is still mentioned in the code comments but it was removed: https://github.com/mapbox/feature-filter/pull/12#r51309070 - looks like nobody could remember why it was there. It would be good to support filtering tiles generated by geojson-vt, either by changing geojson-vt to use `properties` (which would also require changes to vt-pbf) or changing this back to check `f.tags` too.

Migrated from https://github.com/mapbox/feature-filter/issues/20

**Comment by mourner** [comment]
I think we should migrate to using `properties` everywhere for consistency. cc @gmaclennan

**Comment by mourner** [comment]
-> https://github.com/mapbox/geojson-vt/issues/80
