### ISSUE TITLE
Prohibit ["has", "$type"] and ["!has", "$type"]

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#643]
We have [a validation](https://github.com/mapbox/mapbox-gl-style-spec/blob/b87a7bb2b073cace5fb42cb6b515af4fbd1a11ca/lib/validate/validate_filter.js#L38-L38) prohibiting comparison operators with `$type`. This prohibition should extend to `has` and `!has` as well.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4164
