### ISSUE TITLE
Add support for more geometry types in feature-filter

### ISSUE THREAD

**Issue by fuzhenn** [mapbox/mapbox-gl-style-spec#644]
feature-filter only supports basic geometry types now:
https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/lib/feature_filter/index.js#L5
```javascript
var types = ['Unknown', 'Point', 'LineString', 'Polygon'];
```

Could you consider to add support for the following types?
``` javascript
['MultiPoint', 'MultiLineString', 'MultiPolygon', 'GeometryCollection']
```

It would be very useful for third-parties to integrate "feature-filter" into their projects.

Thanks!

**Comment by tmcw** [comment]
Thanks for the suggestion, Fu! If you need functionality outside of style-spec's goals (specifically, to support the types in vector tiles and the syntax in the style spec), I'd recommend forking the project. This project is focused closely on the goals of Mapbox GL, and functionality that doesn't line up with that aim would likely go unmaintained.
