### ISSUE TITLE
Rename circle-pitch-scale to circle-scale-alignment

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#645]
`circle-pitch-scale` should be renamed `circle-scale-alignment`.

https://github.com/mapbox/mapbox-gl-style-spec/issues/459#issuecomment-224957055 proposed `{circle,icon,text}-pitch-scale` properties as complements to the `{circle,icon,text}-{rotation,pitch}-alignment` properties. As discussed in mapbox/mapbox-gl-native#6098, the `circle-pitch-scale` name incorrectly implies a numeric value. It’s also inconsistent with the rest of the properties:

Property |  | a feature’s | according to the map or viewport’s | when the map has
----|----|----|----|----
`circle-rotation-alignment` | **aligns** | **rotation** | **rotation** | rotation
`circle-pitch-alignment` | **aligns** | **pitch** | **pitch** | pitch
`circle-pitch-scale` | aligns | **scale** | **scale** | **pitch**

Renaming `circle-pitch-scale` to `circle-scale-alignment` would make the property’s type more obvious and better harmonize the name with the others:

Property | does what | a feature’s | according to the map or viewport’s | when
----|----|----|----|----
`circle-scale-alignment` | **aligns** | **scale** | **scale** | pitch

/cc @jfirebaugh @lucaswoj

**Comment by 1ec5** [comment]
An alternative to `*-scale-alignment` would be `*-size-alignment`, which would be consistent with `icon-size` and `text-size`.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4165
