### ISSUE TITLE
Rename line-dasharray to line-dash-array

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#647]
The `line-dasharray` property should be renamed `line-dash-array`. The missing dash really bugs me, and if we were to go through with #638, `lineDasharray` would look sloppy.

/cc @lucaswoj @tmcw

**Comment by 1ec5** [comment]
Note that the iOS and macOS SDKs call this property `lineDashPattern` [for consistency with the platform](https://developer.apple.com/search/?q=lineDashPattern&type=Reference) (and MapKit).

**Comment by mourner** [comment]
AFAIR the original reason there's no dash is that SVG spec doesn't have it too, e.g. https://developer.mozilla.org/ru/docs/Web/SVG/Attribute/stroke-dasharray, and we wanted it to be consistent with existing web specs.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4167
