### ISSUE TITLE
Rename text-size to text-font-size

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-style-spec#650]
The `text-size` property should be renamed `text-font-size`. As part of #218, it would be shortened to `font-size`.

Contrary to the property’s current name, it does not specify the dimensions of the overall label the way `text-max-width` does. Instead, it specifies the font size in pixels. This inconsistency means a developer using the iOS or macOS SDK would be tempted to set the property to a `CGSize` or `NSSize` value instead of a number.

/cc @lucaswoj @jfirebaugh

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4168
