### ISSUE TITLE
Cannot filter properties beginning with '@'

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-style-spec#654]
A Mapbox tileset generated with data exported from OSM overpass has the metadata properties prefixed with `@` eg. `@id`, `@user`. While trying to filter this property, I get the following error:

```
map.setFilter("countries-layer-highlight", ["==", "@id","India" ])
evented.js:91 Error: layers.countries-layer-highlight.filter[1]: filter key cannot be a constant
    at Function.module.exports.emitErrors (validate_style.js:8)
    at t._validate (style.js:807)
    at t.setFilter (style.js:585)
    at e.setFilter (map.js:849)
    at <anonymous>:1:5
```

Is there a workaround to this apart from renaming the property in my tileset?

**Comment by mourner** [comment]
Probably no workaround — we'll have to remove that check in the style-spec validator ([here](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/lib/validate/validate_filter.js)). It was relevant when the spec had the concept of constants, but no longer.

**Comment by ImreSamu** [comment]
same problem with:  [Mapbox OSM QA TILES](http://osmlab.github.io/osm-qa-tiles/)  (`@version` `@user` ...  )
