### ISSUE TITLE
OSM copyright and update link on Mapbox Satellite

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-style-spec#662]
Perhaps not the right to place an issue on this, but I wonder why the attribution for Mapbox Satellite (https://api.mapbox.com/v4/mapbox.satellite.json) contains an OSM copyright notice and an "Improve this map" link. Neither really make sense unless there are vector layers placed on top, but these will be provided by other sources which also contain these references.

If one only renders a clean satellite map it makes more sense to make the attribution "© Mapbox | © DigitalGlobe".

**Comment by jfirebaugh** [comment]
The water mask of Mapbox Satellite is calculated using OpenStreetMap data -- for example coastlines, piers, etc.

**Comment by averas** [comment]
@jfirebaugh Ah, alright.. but the "Improve this map" link? For the same reason? Do you receive updates on the satellite raster maps via https://www.mapbox.com/map-feedback?
