### ISSUE TITLE
Support more than two values for `line-dasharray`?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-style-spec#72]
Would it be possible to support more than two values in an array for `line-dasharray`, in order to create more complex patterns?:

![screen shot 2014-06-30 at 3 22 10 pm](https://cloud.githubusercontent.com/assets/5607844/3434599/ecb35d36-008b-11e4-8b8c-dd892a7053b3.png)

**Comment by jfirebaugh** [comment]
This is part of #234.
